import assert from 'node:assert/strict';
import http from 'node:http';
import test from 'node:test';
import { createApp } from './app';
import { httpTestAuth, tokenFor as es256TokenFor } from './test-resource-auth';
import type { AuthContext } from '../auth/authorization';
import type { OpportunityParticipantService } from '../resources/opportunity-participant/contracts';

const token = es256TokenFor;
const participant=()=>({id:11,opportunityId:21,accountId:31,businessId:null,participationRole:'responder' as const,participationStatus:'invited' as const,createdBy:10,createdAt:new Date(),updatedAt:new Date()});
const service=(o:Partial<OpportunityParticipantService>={}):OpportunityParticipantService=>({createParticipant:async()=>participant(),getParticipant:async()=>participant(),listOpportunityParticipants:async()=>[participant()],updateParticipant:async()=>{throw new Error('Participant updates are not supported until a concrete transition authority is qualified')},...o});
const start=async(s:OpportunityParticipantService,c?:AuthContext)=>{const app=createApp({ resourceAuthMiddleware: httpTestAuth,opportunityParticipantService:s});app.use((req,_res,next)=>{if(c)req.authContext=c;next()});const server=http.createServer(app);await new Promise<void>(r=>server.listen(0,'127.0.0.1',r));const a=server.address();assert.ok(a&&typeof a!=='string');return{server,baseUrl:`http://127.0.0.1:${a.port}`}};
const close=(s:http.Server)=>new Promise<void>(r=>s.close(()=>r()));

test('participant list requires authentication',async()=>{const{server,baseUrl}=await start(service());try{const r=await fetch(`${baseUrl}/api/v1/opportunities/21/participants`);assert.equal(r.status,401)}finally{await close(server)}});
test('participant list binds opportunity and context',async()=>{let seen:AuthContext|undefined;const{server,baseUrl}=await start(service({listOpportunityParticipants:async(c,id)=>{seen=c;assert.equal(id,21);return[participant()]}}),{userId:10,role:'business'});try{const r=await fetch(`${baseUrl}/api/v1/opportunities/21/participants`,{headers:{Authorization:`Bearer ${token({userId:10,role:'business'})}`}});assert.equal(r.status,200);assert.equal((await r.json() as any).participants[0].id,11);assert.deepEqual(seen,{userId:10,role:'business'})}finally{await close(server)}});
test('participant read validates id and maps not found',async()=>{const{server,baseUrl}=await start(service({getParticipant:async()=>null}),{userId:10,role:'business'});try{let r=await fetch(`${baseUrl}/api/v1/opportunity-participants/0`,{headers:{Authorization:`Bearer ${token({userId:10,role:'business'})}`}});assert.equal(r.status,400);r=await fetch(`${baseUrl}/api/v1/opportunity-participants/11`,{headers:{Authorization:`Bearer ${token({userId:10,role:'business'})}`}});assert.equal(r.status,404)}finally{await close(server)}});
test('participant creation uses canonical input and rejects server-owned fields',async()=>{let seen:unknown;const{server,baseUrl}=await start(service({createParticipant:async(_c,input)=>{seen=input;return participant()}}),{userId:10,role:'business'});try{let r=await fetch(`${baseUrl}/api/v1/opportunity-participants`,{method:'POST',headers:{Authorization:`Bearer ${token({userId:10,role:'business'})}`,'Content-Type':'application/json'},body:JSON.stringify({opportunityId:21,accountId:31,participationRole:'responder',participationStatus:'invited',id:99,createdBy:99})});assert.equal(r.status,400);r=await fetch(`${baseUrl}/api/v1/opportunity-participants`,{method:'POST',headers:{Authorization:`Bearer ${token({userId:10,role:'business'})}`,'Content-Type':'application/json'},body:JSON.stringify({opportunityId:21,accountId:31,participationRole:'responder',participationStatus:'invited'})});assert.equal(r.status,201);assert.deepEqual(seen,{opportunityId:21,accountId:31,participationRole:'responder',participationStatus:'invited'})}finally{await close(server)}});
test('participant update is not exposed before transition authority qualification',async()=>{const{server,baseUrl}=await start(service(),{userId:10,role:'business'});try{const r=await fetch(`${baseUrl}/api/v1/opportunity-participants/11`,{method:'PATCH',headers:{Authorization:`Bearer ${token({userId:10,role:'business'})}`,'Content-Type':'application/json'},body:JSON.stringify({participationStatus:'active'})});assert.equal(r.status,404)}finally{await close(server)}});
