-- Contact Access Slice A: dedicated entitlement persistence for Model A
-- (Business + Opportunity), promotional/manual grants only.
-- Construction-only for domain grant/check/revoke. No HTTP, payment,
-- provider, disclosure, or Enquiry redaction is authorized by this migration.

CREATE TABLE ghm.contact_access_entitlement (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  business_id bigint NOT NULL
    REFERENCES ghm.business(id)
    ON DELETE RESTRICT,

  opportunity_id bigint NOT NULL
    REFERENCES ghm.opportunity(id)
    ON DELETE RESTRICT,

  authorization_status text NOT NULL,

  grant_reason text NOT NULL,
  grant_source text NOT NULL,
  granted_by_account_id bigint
    REFERENCES ghm.account_identity(id)
    ON DELETE SET NULL,
  granted_at timestamptz NOT NULL DEFAULT now(),

  -- Future commercial-event linkage; unused by Slice A grant path.
  commercial_event_reference text,

  revoked_at timestamptz,
  revoked_by_account_id bigint
    REFERENCES ghm.account_identity(id)
    ON DELETE SET NULL,
  revocation_reason text,

  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT contact_access_authorization_status_valid
    CHECK (authorization_status IN ('active', 'revoked')),

  CONSTRAINT contact_access_grant_reason_valid
    CHECK (grant_reason = 'manual_promotional'),

  CONSTRAINT contact_access_grant_source_valid
    CHECK (length(btrim(grant_source)) BETWEEN 1 AND 100),

  CONSTRAINT contact_access_commercial_event_reference_valid
    CHECK (
      commercial_event_reference IS NULL
      OR length(btrim(commercial_event_reference)) BETWEEN 1 AND 200
    ),

  CONSTRAINT contact_access_revocation_reason_valid
    CHECK (
      revocation_reason IS NULL
      OR length(btrim(revocation_reason)) BETWEEN 1 AND 500
    ),

  CONSTRAINT contact_access_active_revocation_null
    CHECK (
      (
        authorization_status = 'active'
        AND revoked_at IS NULL
        AND revoked_by_account_id IS NULL
        AND revocation_reason IS NULL
      )
      OR (
        authorization_status = 'revoked'
        AND revoked_at IS NOT NULL
        AND revocation_reason IS NOT NULL
      )
    )
);

-- At most one active Contact Access entitlement per Business + Opportunity.
CREATE UNIQUE INDEX contact_access_one_active_uq
  ON ghm.contact_access_entitlement (business_id, opportunity_id)
  WHERE authorization_status = 'active';

CREATE INDEX contact_access_business_opportunity_idx
  ON ghm.contact_access_entitlement (business_id, opportunity_id, granted_at DESC, id DESC);

CREATE INDEX contact_access_opportunity_idx
  ON ghm.contact_access_entitlement (opportunity_id, id);

CREATE TABLE ghm.contact_access_event (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  entitlement_id bigint NOT NULL
    REFERENCES ghm.contact_access_entitlement(id)
    ON DELETE RESTRICT,

  business_id bigint NOT NULL
    REFERENCES ghm.business(id)
    ON DELETE RESTRICT,

  opportunity_id bigint NOT NULL
    REFERENCES ghm.opportunity(id)
    ON DELETE RESTRICT,

  event_type text NOT NULL,
  actor_account_id bigint
    REFERENCES ghm.account_identity(id)
    ON DELETE SET NULL,
  source text NOT NULL,
  reason text NOT NULL,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  occurred_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT contact_access_event_type_valid
    CHECK (event_type IN ('granted', 'revoked')),

  CONSTRAINT contact_access_event_source_valid
    CHECK (length(btrim(source)) BETWEEN 1 AND 100),

  CONSTRAINT contact_access_event_reason_valid
    CHECK (length(btrim(reason)) BETWEEN 1 AND 500),

  CONSTRAINT contact_access_event_payload_object
    CHECK (jsonb_typeof(payload) = 'object')
);

CREATE INDEX contact_access_event_entitlement_idx
  ON ghm.contact_access_event (entitlement_id, occurred_at DESC, id DESC);

CREATE INDEX contact_access_event_business_opportunity_idx
  ON ghm.contact_access_event (business_id, opportunity_id, occurred_at DESC, id DESC);

ALTER TABLE ghm.contact_access_entitlement OWNER TO ghm_schema_owner;
ALTER TABLE ghm.contact_access_event OWNER TO ghm_schema_owner;

CREATE OR REPLACE FUNCTION ghm.touch_contact_access_entitlement()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

ALTER FUNCTION ghm.touch_contact_access_entitlement() OWNER TO ghm_schema_owner;

CREATE TRIGGER contact_access_entitlement_updated_at
BEFORE UPDATE ON ghm.contact_access_entitlement
FOR EACH ROW
EXECUTE FUNCTION ghm.touch_contact_access_entitlement();

GRANT USAGE ON SCHEMA ghm TO ghm_runtime;

GRANT SELECT
  ON TABLE ghm.contact_access_entitlement
  TO ghm_runtime;

GRANT SELECT
  ON TABLE ghm.contact_access_event
  TO ghm_runtime;

REVOKE INSERT, UPDATE, DELETE
  ON TABLE ghm.contact_access_entitlement
  FROM ghm_runtime;

REVOKE INSERT, UPDATE, DELETE
  ON TABLE ghm.contact_access_event
  FROM ghm_runtime;

GRANT SELECT, INSERT, UPDATE, DELETE ON
  ghm.contact_access_entitlement,
  ghm.contact_access_event
TO ghm_migrator;

GRANT USAGE, SELECT ON SEQUENCE
  ghm.contact_access_entitlement_id_seq,
  ghm.contact_access_event_id_seq
TO ghm_migrator;

CREATE OR REPLACE FUNCTION ghm.grant_contact_access_manual(
  p_business_id bigint,
  p_opportunity_id bigint,
  p_grant_source text
)
RETURNS TABLE (
  id bigint,
  business_id bigint,
  opportunity_id bigint,
  authorization_status text,
  grant_reason text,
  grant_source text,
  granted_by_account_id bigint,
  granted_at timestamptz,
  commercial_event_reference text,
  revoked_at timestamptz,
  revoked_by_account_id bigint,
  revocation_reason text,
  created_at timestamptz,
  updated_at timestamptz
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, ghm
AS $$
DECLARE
  normalized_source text;
  opportunity_lifecycle text;
  enquiry_count integer;
  enquiry_business_id bigint;
  actor_account_id bigint;
  existing ghm.contact_access_entitlement%ROWTYPE;
  inserted ghm.contact_access_entitlement%ROWTYPE;
BEGIN
  BEGIN
    actor_account_id := nullif(btrim(current_setting('ghm.actor_account_id', true)), '')::bigint;
  EXCEPTION
    WHEN invalid_text_representation THEN
      RAISE EXCEPTION 'Contact Access actor context required';
  END;

  IF actor_account_id IS NULL OR actor_account_id <= 0 THEN
    RAISE EXCEPTION 'Contact Access actor context required';
  END IF;

  IF p_business_id IS NULL OR p_business_id <= 0 THEN
    RAISE EXCEPTION 'businessId must be a positive integer';
  END IF;

  IF p_opportunity_id IS NULL OR p_opportunity_id <= 0 THEN
    RAISE EXCEPTION 'opportunityId must be a positive integer';
  END IF;

  normalized_source := btrim(p_grant_source);
  IF normalized_source IS NULL OR length(normalized_source) < 1 OR length(normalized_source) > 100 THEN
    RAISE EXCEPTION 'grantSource must be between 1 and 100 characters';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM ghm.business b
     WHERE b.id = p_business_id
       AND b.is_active = true
  ) THEN
    RAISE EXCEPTION 'Business is not eligible for Contact Access';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM ghm.business_membership bm
     WHERE bm.business_id = p_business_id
       AND bm.account_id = actor_account_id
       AND bm.membership_status = 'active'
       AND bm.membership_role IN ('owner', 'administrator')
  ) THEN
    RAISE EXCEPTION 'Business management permission required';
  END IF;

  SELECT o.lifecycle_status INTO opportunity_lifecycle
    FROM ghm.opportunity o
   WHERE o.id = p_opportunity_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Opportunity not found';
  END IF;

  IF opportunity_lifecycle NOT IN ('open', 'responding', 'evaluating') THEN
    RAISE EXCEPTION 'Opportunity is not eligible for Contact Access grant';
  END IF;

  SELECT COUNT(*), MIN(e.business_id)
    INTO enquiry_count, enquiry_business_id
    FROM ghm.enquiry e
   WHERE e.opportunity_id = p_opportunity_id;

  IF enquiry_count = 0 THEN
    RAISE EXCEPTION 'Opportunity is not Enquiry-backed';
  END IF;

  IF enquiry_count > 1 THEN
    RAISE EXCEPTION 'Opportunity Enquiry association is ambiguous';
  END IF;

  IF enquiry_business_id IS DISTINCT FROM p_business_id THEN
    RAISE EXCEPTION 'Contact Access Business does not match Enquiry recipient';
  END IF;

  -- Serialize concurrent grants for the same Business+Opportunity pair.
  PERFORM pg_advisory_xact_lock(
    hashtext('ghm.contact_access.grant.business:' || p_business_id::text),
    hashtext('ghm.contact_access.grant.opportunity:' || p_opportunity_id::text)
  );

  SELECT * INTO existing
    FROM ghm.contact_access_entitlement cae
   WHERE cae.business_id = p_business_id
     AND cae.opportunity_id = p_opportunity_id
     AND cae.authorization_status = 'active'
   FOR UPDATE;

  IF FOUND THEN
    RETURN QUERY
    SELECT
      existing.id,
      existing.business_id,
      existing.opportunity_id,
      existing.authorization_status,
      existing.grant_reason,
      existing.grant_source,
      existing.granted_by_account_id,
      existing.granted_at,
      existing.commercial_event_reference,
      existing.revoked_at,
      existing.revoked_by_account_id,
      existing.revocation_reason,
      existing.created_at,
      existing.updated_at;
    RETURN;
  END IF;

  BEGIN
    INSERT INTO ghm.contact_access_entitlement (
      business_id,
      opportunity_id,
      authorization_status,
      grant_reason,
      grant_source,
      granted_by_account_id,
      granted_at
    ) VALUES (
      p_business_id,
      p_opportunity_id,
      'active',
      'manual_promotional',
      normalized_source,
      actor_account_id,
      now()
    )
    RETURNING * INTO inserted;
  EXCEPTION
    WHEN unique_violation THEN
      SELECT * INTO existing
        FROM ghm.contact_access_entitlement cae
       WHERE cae.business_id = p_business_id
         AND cae.opportunity_id = p_opportunity_id
         AND cae.authorization_status = 'active'
       FOR UPDATE;

      IF NOT FOUND THEN
        RAISE;
      END IF;

      RETURN QUERY
      SELECT
        existing.id,
        existing.business_id,
        existing.opportunity_id,
        existing.authorization_status,
        existing.grant_reason,
        existing.grant_source,
        existing.granted_by_account_id,
        existing.granted_at,
        existing.commercial_event_reference,
        existing.revoked_at,
        existing.revoked_by_account_id,
        existing.revocation_reason,
        existing.created_at,
        existing.updated_at;
      RETURN;
  END;

  INSERT INTO ghm.contact_access_event (
    entitlement_id,
    business_id,
    opportunity_id,
    event_type,
    actor_account_id,
    source,
    reason,
    payload
  ) VALUES (
    inserted.id,
    inserted.business_id,
    inserted.opportunity_id,
    'granted',
    actor_account_id,
    normalized_source,
    'manual_promotional',
    jsonb_build_object('grant_reason', 'manual_promotional')
  );

  RETURN QUERY
  SELECT
    inserted.id,
    inserted.business_id,
    inserted.opportunity_id,
    inserted.authorization_status,
    inserted.grant_reason,
    inserted.grant_source,
    inserted.granted_by_account_id,
    inserted.granted_at,
    inserted.commercial_event_reference,
    inserted.revoked_at,
    inserted.revoked_by_account_id,
    inserted.revocation_reason,
    inserted.created_at,
    inserted.updated_at;
END;
$$;

ALTER FUNCTION ghm.grant_contact_access_manual(bigint, bigint, text)
  OWNER TO ghm_schema_owner;
REVOKE ALL ON FUNCTION ghm.grant_contact_access_manual(bigint, bigint, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION ghm.grant_contact_access_manual(bigint, bigint, text) TO ghm_runtime;

CREATE OR REPLACE FUNCTION ghm.revoke_contact_access(
  p_business_id bigint,
  p_opportunity_id bigint,
  p_revocation_reason text
)
RETURNS TABLE (
  id bigint,
  business_id bigint,
  opportunity_id bigint,
  authorization_status text,
  grant_reason text,
  grant_source text,
  granted_by_account_id bigint,
  granted_at timestamptz,
  commercial_event_reference text,
  revoked_at timestamptz,
  revoked_by_account_id bigint,
  revocation_reason text,
  created_at timestamptz,
  updated_at timestamptz
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, ghm
AS $$
DECLARE
  normalized_reason text;
  actor_account_id bigint;
  existing ghm.contact_access_entitlement%ROWTYPE;
  updated ghm.contact_access_entitlement%ROWTYPE;
BEGIN
  BEGIN
    actor_account_id := nullif(btrim(current_setting('ghm.actor_account_id', true)), '')::bigint;
  EXCEPTION
    WHEN invalid_text_representation THEN
      RAISE EXCEPTION 'Contact Access actor context required';
  END;

  IF actor_account_id IS NULL OR actor_account_id <= 0 THEN
    RAISE EXCEPTION 'Contact Access actor context required';
  END IF;

  IF p_business_id IS NULL OR p_business_id <= 0 THEN
    RAISE EXCEPTION 'businessId must be a positive integer';
  END IF;

  IF p_opportunity_id IS NULL OR p_opportunity_id <= 0 THEN
    RAISE EXCEPTION 'opportunityId must be a positive integer';
  END IF;

  normalized_reason := btrim(p_revocation_reason);
  IF normalized_reason IS NULL OR length(normalized_reason) < 1 OR length(normalized_reason) > 500 THEN
    RAISE EXCEPTION 'revocationReason must be between 1 and 500 characters';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM ghm.business_membership bm
     WHERE bm.business_id = p_business_id
       AND bm.account_id = actor_account_id
       AND bm.membership_status = 'active'
       AND bm.membership_role IN ('owner', 'administrator')
  ) THEN
    RAISE EXCEPTION 'Business management permission required';
  END IF;

  SELECT * INTO existing
    FROM ghm.contact_access_entitlement cae
   WHERE cae.business_id = p_business_id
     AND cae.opportunity_id = p_opportunity_id
     AND cae.authorization_status = 'active'
   FOR UPDATE;

  IF NOT FOUND THEN
    IF EXISTS (
      SELECT 1 FROM ghm.contact_access_entitlement cae
       WHERE cae.business_id = p_business_id
         AND cae.opportunity_id = p_opportunity_id
         AND cae.authorization_status = 'revoked'
    ) THEN
      RAISE EXCEPTION 'Contact Access entitlement is not active';
    END IF;
    RAISE EXCEPTION 'Contact Access entitlement not found';
  END IF;

  UPDATE ghm.contact_access_entitlement
     SET authorization_status = 'revoked',
         revoked_at = now(),
         revoked_by_account_id = actor_account_id,
         revocation_reason = normalized_reason
   WHERE ghm.contact_access_entitlement.id = existing.id
  RETURNING * INTO updated;

  INSERT INTO ghm.contact_access_event (
    entitlement_id,
    business_id,
    opportunity_id,
    event_type,
    actor_account_id,
    source,
    reason,
    payload
  ) VALUES (
    updated.id,
    updated.business_id,
    updated.opportunity_id,
    'revoked',
    actor_account_id,
    'manual_revoke',
    normalized_reason,
    jsonb_build_object('prior_status', 'active')
  );

  RETURN QUERY
  SELECT
    updated.id,
    updated.business_id,
    updated.opportunity_id,
    updated.authorization_status,
    updated.grant_reason,
    updated.grant_source,
    updated.granted_by_account_id,
    updated.granted_at,
    updated.commercial_event_reference,
    updated.revoked_at,
    updated.revoked_by_account_id,
    updated.revocation_reason,
    updated.created_at,
    updated.updated_at;
END;
$$;

ALTER FUNCTION ghm.revoke_contact_access(bigint, bigint, text)
  OWNER TO ghm_schema_owner;
REVOKE ALL ON FUNCTION ghm.revoke_contact_access(bigint, bigint, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION ghm.revoke_contact_access(bigint, bigint, text) TO ghm_runtime;
