-- Migration reset-enrollment state for credentialless QuoteFlow accounts.
-- This is migration provenance/enrollment state, not runtime identity ownership.

CREATE TABLE IF NOT EXISTS ghm.quoteflow_migration_reset_enrollment (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id bigint NOT NULL REFERENCES ghm.account_identity(id),
  source_provider text NOT NULL,
  source_subject text NOT NULL,
  approved_email text NOT NULL,
  approved_email_normalized text NOT NULL,
  source_evidence_reference text NOT NULL,
  enrollment_status text NOT NULL DEFAULT 'reset_required',
  created_at timestamptz NOT NULL DEFAULT current_timestamp,
  updated_at timestamptz NOT NULL DEFAULT current_timestamp,
  CONSTRAINT quoteflow_migration_reset_enrollment_provider_check
    CHECK (source_provider = 'supabase'),
  CONSTRAINT quoteflow_migration_reset_enrollment_subject_check
    CHECK (btrim(source_subject) <> ''),
  CONSTRAINT quoteflow_migration_reset_enrollment_email_check
    CHECK (btrim(approved_email) <> '' AND btrim(approved_email_normalized) <> ''),
  CONSTRAINT quoteflow_migration_reset_enrollment_status_check
    CHECK (enrollment_status IN ('reset_required', 'completed')),
  CONSTRAINT quoteflow_migration_reset_enrollment_source_unique
    UNIQUE (source_provider, source_subject),
  CONSTRAINT quoteflow_migration_reset_enrollment_email_unique
    UNIQUE (approved_email_normalized),
  CONSTRAINT quoteflow_migration_reset_enrollment_account_unique
    UNIQUE (account_id)
);

CREATE INDEX IF NOT EXISTS quoteflow_migration_reset_enrollment_status_email_idx
  ON ghm.quoteflow_migration_reset_enrollment (enrollment_status, approved_email_normalized);

CREATE OR REPLACE FUNCTION ghm.auth_register_quoteflow_migration_reset_enrollment(
  p_account_id bigint,
  p_provider text,
  p_subject text,
  p_approved_email text,
  p_approved_email_normalized text,
  p_source_evidence_reference text
) RETURNS TABLE (
  outcome text,
  enrollment_id bigint
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, ghm, pg_temp
AS $$
DECLARE
  v_existing ghm.quoteflow_migration_reset_enrollment%ROWTYPE;
  v_identity ghm.account_identity%ROWTYPE;
BEGIN
  IF p_account_id IS NULL OR p_account_id <= 0 THEN
    RAISE EXCEPTION 'account id must be positive' USING ERRCODE = '22023';
  END IF;
  IF p_provider <> 'supabase' THEN
    RAISE EXCEPTION 'migration provider must be supabase' USING ERRCODE = '22023';
  END IF;
  IF p_subject IS NULL OR btrim(p_subject) = '' THEN
    RAISE EXCEPTION 'subject must be non-blank' USING ERRCODE = '22023';
  END IF;
  IF p_approved_email IS NULL OR btrim(p_approved_email) = ''
     OR p_approved_email_normalized IS NULL OR btrim(p_approved_email_normalized) = '' THEN
    RAISE EXCEPTION 'approved email is required' USING ERRCODE = '22023';
  END IF;
  IF p_source_evidence_reference IS NULL OR btrim(p_source_evidence_reference) = '' THEN
    RAISE EXCEPTION 'source evidence reference is required' USING ERRCODE = '22023';
  END IF;

  SELECT * INTO v_identity
    FROM ghm.account_identity
   WHERE id = p_account_id
     AND account_status = 'active';

  IF NOT FOUND THEN
    RAISE EXCEPTION 'migration account is not active' USING ERRCODE = 'P0001';
  END IF;

  IF v_identity.login_email_normalized <> p_approved_email_normalized THEN
    RAISE EXCEPTION 'migration approved email does not match canonical account email' USING ERRCODE = 'P0001';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM ghm.account_external_identity
     WHERE provider = p_provider
       AND subject = p_subject
       AND account_id = p_account_id
  ) THEN
    RAISE EXCEPTION 'migration external identity mapping mismatch' USING ERRCODE = 'P0001';
  END IF;

  SELECT * INTO v_existing
    FROM ghm.quoteflow_migration_reset_enrollment
   WHERE account_id = p_account_id
      OR (source_provider = p_provider AND source_subject = p_subject)
      OR approved_email_normalized = p_approved_email_normalized
   FOR UPDATE;

  IF FOUND THEN
    IF v_existing.account_id = p_account_id
       AND v_existing.source_provider = p_provider
       AND v_existing.source_subject = p_subject
       AND v_existing.approved_email_normalized = p_approved_email_normalized
       AND v_existing.source_evidence_reference = p_source_evidence_reference THEN
      outcome := 'already_registered';
      enrollment_id := v_existing.id;
      RETURN NEXT;
      RETURN;
    END IF;
    RAISE EXCEPTION 'migration reset enrollment conflict' USING ERRCODE = 'P0001';
  END IF;

  INSERT INTO ghm.quoteflow_migration_reset_enrollment (
    account_id,
    source_provider,
    source_subject,
    approved_email,
    approved_email_normalized,
    source_evidence_reference,
    enrollment_status
  ) VALUES (
    p_account_id,
    p_provider,
    p_subject,
    btrim(p_approved_email),
    btrim(p_approved_email_normalized),
    btrim(p_source_evidence_reference),
    'reset_required'
  )
  RETURNING id INTO enrollment_id;

  outcome := 'created';
  RETURN NEXT;
END;
$$;

ALTER FUNCTION ghm.auth_register_quoteflow_migration_reset_enrollment(
  bigint, text, text, text, text, text
) OWNER TO ghm_schema_owner;

REVOKE ALL ON FUNCTION ghm.auth_register_quoteflow_migration_reset_enrollment(
  bigint, text, text, text, text, text
) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION ghm.auth_register_quoteflow_migration_reset_enrollment(
  bigint, text, text, text, text, text
) TO ghm_runtime;

REVOKE ALL ON TABLE ghm.quoteflow_migration_reset_enrollment FROM PUBLIC;
REVOKE INSERT, UPDATE, DELETE ON TABLE ghm.quoteflow_migration_reset_enrollment FROM ghm_runtime;

COMMENT ON TABLE ghm.quoteflow_migration_reset_enrollment IS
  'Migration-only QuoteFlow reset/re-enrollment provenance. Not a runtime identity or generic recovery-email store.';
