CREATE TABLE ghm.quote (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id bigint NOT NULL
    REFERENCES ghm.account_identity(id)
    ON DELETE CASCADE,
  customer_id bigint NOT NULL
    REFERENCES ghm.customer(id),
  customer_name text NOT NULL,
  customer_phone text,
  customer_email text,
  description text NOT NULL,
  amount numeric NOT NULL,
  follow_up_date date NOT NULL,
  status text NOT NULL DEFAULT 'active',
  reminder_id text,
  reminder_date date,
  notes text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT quote_description_nonblank_ck CHECK (char_length(btrim(description)) > 0),
  CONSTRAINT quote_amount_positive_ck CHECK (amount > 0),
  CONSTRAINT quote_status_ck CHECK (status IN ('active', 'won', 'lost')),
  CONSTRAINT quote_reminder_pair_ck CHECK ((reminder_id IS NULL) = (reminder_date IS NULL))
);

CREATE TABLE ghm.quote_line_item (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  quote_id bigint NOT NULL
    REFERENCES ghm.quote(id)
    ON DELETE CASCADE,
  description text NOT NULL,
  quantity numeric(14,4) NOT NULL,
  unit_price numeric(14,2) NOT NULL,
  catalog_item_id bigint NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT quote_line_item_description_nonblank_ck CHECK (char_length(btrim(description)) > 0),
  CONSTRAINT quote_line_item_quantity_positive_ck CHECK (quantity > 0),
  CONSTRAINT quote_line_item_unit_price_positive_ck CHECK (unit_price > 0)
);

CREATE INDEX quote_account_created_idx ON ghm.quote (account_id, created_at DESC);
CREATE INDEX quote_account_status_follow_up_idx ON ghm.quote (account_id, status, follow_up_date);
CREATE INDEX quote_customer_created_idx ON ghm.quote (customer_id, created_at DESC);
CREATE INDEX quote_line_item_quote_id_idx ON ghm.quote_line_item (quote_id, id);

GRANT USAGE ON SCHEMA ghm TO ghm_runtime;
GRANT SELECT ON TABLE ghm.quote, ghm.quote_line_item TO ghm_runtime;
GRANT INSERT (account_id, customer_id, customer_name, customer_phone, customer_email, description, amount, follow_up_date)
  ON TABLE ghm.quote TO ghm_runtime;
GRANT INSERT (quote_id, description, quantity, unit_price, catalog_item_id)
  ON TABLE ghm.quote_line_item TO ghm_runtime;
GRANT UPDATE (status, reminder_id, reminder_date, notes, updated_at)
  ON TABLE ghm.quote TO ghm_runtime;
GRANT USAGE ON SEQUENCE ghm.quote_id_seq, ghm.quote_line_item_id_seq TO ghm_runtime;
ALTER DEFAULT PRIVILEGES FOR ROLE ghm_schema_owner IN SCHEMA ghm
  GRANT USAGE ON SEQUENCES TO ghm_runtime;

-- Runtime DELETE is intentionally not granted.
-- Runtime updates are constrained by the service contract; ACLs are limited to status/reminder/notes fields.
