-- Commercial schema construction.
-- Contract:
-- docs/architecture/COMMERCIAL_MINIMUM_SCHEMA_CONTRACT.md
--
-- Provider-neutral commercial state for Business-scoped subscriptions,
-- trials, payments, provider events, commercial events, and founding
-- allocations.
--
-- No provider-specific schema.
-- No product-specific Supabase structures.
-- No production cutover authority.

CREATE TABLE ghm.commercial_plan (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code text NOT NULL UNIQUE,
  name text NOT NULL,
  audience text NOT NULL DEFAULT 'business',
  lifecycle_status text NOT NULL DEFAULT 'draft',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT commercial_plan_code_valid
    CHECK (code = lower(code) AND code ~ '^[a-z][a-z0-9_]{2,49}$'),

  CONSTRAINT commercial_plan_name_valid
    CHECK (length(btrim(name)) BETWEEN 2 AND 100),

  CONSTRAINT commercial_plan_audience_valid
    CHECK (audience = 'business'),

  CONSTRAINT commercial_plan_lifecycle_valid
    CHECK (lifecycle_status IN ('draft', 'active', 'retired'))
);

CREATE TABLE ghm.commercial_plan_version (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plan_id bigint NOT NULL
    REFERENCES ghm.commercial_plan(id)
    ON DELETE RESTRICT,
  version integer NOT NULL,
  trial_days integer NOT NULL DEFAULT 0,
  founding_limit integer,
  founding_protection_months integer,
  effective_from timestamptz NOT NULL,
  effective_until timestamptz,
  lifecycle_status text NOT NULL DEFAULT 'draft',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT commercial_plan_version_version_valid
    CHECK (version >= 1),

  CONSTRAINT commercial_plan_version_trial_days_valid
    CHECK (trial_days BETWEEN 0 AND 30),

  CONSTRAINT commercial_plan_version_founding_limit_valid
    CHECK (founding_limit IS NULL OR founding_limit > 0),

  CONSTRAINT commercial_plan_version_founding_protection_valid
    CHECK (
      founding_protection_months IS NULL
      OR founding_protection_months BETWEEN 1 AND 60
    ),

  CONSTRAINT commercial_plan_version_effective_range_valid
    CHECK (
      effective_until IS NULL
      OR effective_until > effective_from
    ),

  CONSTRAINT commercial_plan_version_lifecycle_valid
    CHECK (lifecycle_status IN ('draft', 'active', 'retired')),

  CONSTRAINT commercial_plan_version_unique
    UNIQUE (plan_id, version)
);

CREATE TABLE ghm.commercial_plan_entitlement (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plan_version_id bigint NOT NULL
    REFERENCES ghm.commercial_plan_version(id)
    ON DELETE CASCADE,
  entitlement_code text NOT NULL,
  access_level text NOT NULL DEFAULT 'enabled',
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT commercial_plan_entitlement_code_valid
    CHECK (
      entitlement_code ~ '^[a-z][a-z0-9.]{2,99}$'
    ),

  CONSTRAINT commercial_plan_entitlement_access_level_valid
    CHECK (access_level = 'enabled'),

  CONSTRAINT commercial_plan_entitlement_metadata_object
    CHECK (jsonb_typeof(metadata) = 'object'),

  CONSTRAINT commercial_plan_entitlement_unique
    UNIQUE (plan_version_id, entitlement_code)
);

CREATE TABLE ghm.commercial_plan_price (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  plan_version_id bigint NOT NULL
    REFERENCES ghm.commercial_plan_version(id)
    ON DELETE RESTRICT,
  country_id bigint
    REFERENCES ghm.country(id)
    ON DELETE RESTRICT,
  currency_id bigint NOT NULL
    REFERENCES ghm.currency(id)
    ON DELETE RESTRICT,
  price_kind text NOT NULL,
  amount_minor_units bigint NOT NULL,
  billing_interval text NOT NULL DEFAULT 'month',
  effective_from timestamptz NOT NULL,
  effective_until timestamptz,
  lifecycle_status text NOT NULL DEFAULT 'draft',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT commercial_plan_price_kind_valid
    CHECK (price_kind IN ('founding', 'standard')),

  CONSTRAINT commercial_plan_price_amount_valid
    CHECK (amount_minor_units >= 0),

  CONSTRAINT commercial_plan_price_billing_interval_valid
    CHECK (billing_interval = 'month'),

  CONSTRAINT commercial_plan_price_effective_range_valid
    CHECK (
      effective_until IS NULL
      OR effective_until > effective_from
    ),

  CONSTRAINT commercial_plan_price_lifecycle_valid
    CHECK (lifecycle_status IN ('draft', 'active', 'retired'))
);

CREATE INDEX commercial_plan_version_effective_idx
  ON ghm.commercial_plan_version (
    plan_id,
    lifecycle_status,
    effective_from,
    effective_until
  );

CREATE INDEX commercial_plan_price_lookup_idx
  ON ghm.commercial_plan_price (
    plan_version_id,
    country_id,
    currency_id,
    price_kind,
    lifecycle_status,
    effective_from
  );

CREATE TABLE ghm.commercial_trial (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id bigint NOT NULL
    REFERENCES ghm.business(id)
    ON DELETE RESTRICT,
  plan_version_id bigint NOT NULL
    REFERENCES ghm.commercial_plan_version(id)
    ON DELETE RESTRICT,
  activated_by bigint NOT NULL
    REFERENCES ghm.account_identity(id)
    ON DELETE RESTRICT,
  activated_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL,
  lifecycle_status text NOT NULL DEFAULT 'active',
  ended_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT commercial_trial_expiry_valid
    CHECK (expires_at > activated_at),

  CONSTRAINT commercial_trial_lifecycle_valid
    CHECK (
      lifecycle_status IN ('active', 'expired', 'converted', 'cancelled')
    ),

  CONSTRAINT commercial_trial_active_ended_at_valid
    CHECK (
      (lifecycle_status = 'active' AND ended_at IS NULL)
      OR
      (lifecycle_status <> 'active' AND ended_at IS NOT NULL)
    ),

  CONSTRAINT commercial_trial_business_unique
    UNIQUE (business_id)
);

CREATE TABLE ghm.commercial_subscription (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id bigint NOT NULL
    REFERENCES ghm.business(id)
    ON DELETE RESTRICT,
  plan_version_id bigint NOT NULL
    REFERENCES ghm.commercial_plan_version(id)
    ON DELETE RESTRICT,
  price_id bigint
    REFERENCES ghm.commercial_plan_price(id)
    ON DELETE RESTRICT,
  trial_id bigint UNIQUE
    REFERENCES ghm.commercial_trial(id)
    ON DELETE RESTRICT,
  lifecycle_status text NOT NULL,
  current_period_start timestamptz,
  current_period_end timestamptz,
  cancel_at_period_end boolean NOT NULL DEFAULT false,
  cancelled_at timestamptz,
  founding_sequence integer,
  founding_protected_until timestamptz,
  provider_reference text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT commercial_subscription_lifecycle_valid
    CHECK (
      lifecycle_status IN (
        'trialing',
        'active',
        'past_due',
        'grace_period',
        'cancel_at_period_end',
        'cancelled',
        'expired',
        'suspended'
      )
    ),

  CONSTRAINT commercial_subscription_period_valid
    CHECK (
      current_period_end IS NULL
      OR (
        current_period_start IS NOT NULL
        AND current_period_end > current_period_start
      )
    ),

  CONSTRAINT commercial_subscription_founding_sequence_valid
    CHECK (
      founding_sequence IS NULL
      OR founding_sequence > 0
    ),

  CONSTRAINT commercial_subscription_cancellation_consistency
    CHECK (
      (
        cancel_at_period_end = true
        AND lifecycle_status = 'cancel_at_period_end'
      )
      OR
      (
        cancel_at_period_end = false
        AND lifecycle_status <> 'cancel_at_period_end'
      )
    ),

  CONSTRAINT commercial_subscription_provider_reference_valid
    CHECK (
      provider_reference IS NULL
      OR length(provider_reference) BETWEEN 1 AND 200
    )

);

CREATE UNIQUE INDEX commercial_subscription_current_business_uq
  ON ghm.commercial_subscription (business_id)
  WHERE lifecycle_status IN (
    'trialing',
    'active',
    'past_due',
    'grace_period',
    'cancel_at_period_end',
    'suspended'
  );

CREATE INDEX commercial_trial_plan_version_idx
  ON ghm.commercial_trial (plan_version_id);

CREATE INDEX commercial_subscription_business_idx
  ON ghm.commercial_subscription (business_id);

CREATE INDEX commercial_subscription_plan_version_idx
  ON ghm.commercial_subscription (plan_version_id);

CREATE INDEX commercial_subscription_status_period_idx
  ON ghm.commercial_subscription (
    lifecycle_status,
    current_period_end
  );

CREATE TABLE ghm.commercial_provider_event (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  provider_code text NOT NULL,
  provider_event_id text NOT NULL,
  event_type text NOT NULL,
  payload_hash text NOT NULL,
  received_at timestamptz NOT NULL DEFAULT now(),
  occurred_at timestamptz,
  processing_status text NOT NULL DEFAULT 'received',
  processed_at timestamptz,
  failure_reason text,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT commercial_provider_event_provider_code_valid
    CHECK (provider_code ~ '^[a-z][a-z0-9_]{1,49}$'),

  CONSTRAINT commercial_provider_event_id_valid
    CHECK (length(provider_event_id) BETWEEN 1 AND 200),

  CONSTRAINT commercial_provider_event_type_valid
    CHECK (length(event_type) BETWEEN 1 AND 100),

  CONSTRAINT commercial_provider_event_payload_hash_valid
    CHECK (payload_hash ~ '^[0-9a-f]{64}$'),

  CONSTRAINT commercial_provider_event_processing_status_valid
    CHECK (
      processing_status IN ('received', 'processed', 'ignored', 'failed')
    ),

  CONSTRAINT commercial_provider_event_processed_at_valid
    CHECK (
      (processing_status = 'received' AND processed_at IS NULL)
      OR
      (processing_status <> 'received' AND processed_at IS NOT NULL)
    ),

  CONSTRAINT commercial_provider_event_failure_reason_valid
    CHECK (
      failure_reason IS NULL
      OR length(failure_reason) BETWEEN 1 AND 1000
    ),

  CONSTRAINT commercial_provider_event_metadata_object
    CHECK (jsonb_typeof(metadata) = 'object'),

  CONSTRAINT commercial_provider_event_identity_unique
    UNIQUE (provider_code, provider_event_id)
);

CREATE INDEX commercial_provider_event_processing_idx
  ON ghm.commercial_provider_event (
    processing_status,
    received_at
  );

CREATE TABLE ghm.commercial_payment_attempt (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id bigint NOT NULL
    REFERENCES ghm.business(id)
    ON DELETE RESTRICT,
  subscription_id bigint
    REFERENCES ghm.commercial_subscription(id)
    ON DELETE RESTRICT,
  price_id bigint NOT NULL
    REFERENCES ghm.commercial_plan_price(id)
    ON DELETE RESTRICT,
  initiated_by bigint NOT NULL
    REFERENCES ghm.account_identity(id)
    ON DELETE RESTRICT,
  attempt_status text NOT NULL DEFAULT 'pending_checkout',
  amount_minor_units bigint NOT NULL,
  currency_id bigint NOT NULL
    REFERENCES ghm.currency(id)
    ON DELETE RESTRICT,
  billing_interval text NOT NULL DEFAULT 'month',
  checkout_reference text,
  idempotency_key text NOT NULL UNIQUE,
  expires_at timestamptz,
  failure_code text,
  failure_message text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT commercial_payment_attempt_status_valid
    CHECK (
      attempt_status IN (
        'pending_checkout',
        'pending_payment',
        'succeeded',
        'failed',
        'expired',
        'cancelled'
      )
    ),

  CONSTRAINT commercial_payment_attempt_amount_valid
    CHECK (amount_minor_units > 0),

  CONSTRAINT commercial_payment_attempt_billing_interval_valid
    CHECK (billing_interval = 'month'),

  CONSTRAINT commercial_payment_attempt_idempotency_key_valid
    CHECK (length(idempotency_key) BETWEEN 8 AND 200),

  CONSTRAINT commercial_payment_attempt_checkout_reference_valid
    CHECK (
      checkout_reference IS NULL
      OR length(checkout_reference) BETWEEN 1 AND 200
    ),

  CONSTRAINT commercial_payment_attempt_failure_code_valid
    CHECK (
      failure_code IS NULL
      OR length(failure_code) BETWEEN 1 AND 100
    ),

  CONSTRAINT commercial_payment_attempt_failure_message_valid
    CHECK (
      failure_message IS NULL
      OR length(failure_message) BETWEEN 1 AND 1000
    ),

  CONSTRAINT commercial_payment_attempt_failed_reason_valid
    CHECK (
      attempt_status <> 'failed'
      OR failure_code IS NOT NULL
    )
);

CREATE INDEX commercial_payment_attempt_business_idx
  ON ghm.commercial_payment_attempt (business_id);

CREATE INDEX commercial_payment_attempt_subscription_idx
  ON ghm.commercial_payment_attempt (subscription_id);

CREATE INDEX commercial_payment_attempt_status_idx
  ON ghm.commercial_payment_attempt (
    attempt_status,
    expires_at
  );

CREATE TABLE ghm.commercial_payment_transaction (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id bigint NOT NULL
    REFERENCES ghm.business(id)
    ON DELETE RESTRICT,
  subscription_id bigint NOT NULL
    REFERENCES ghm.commercial_subscription(id)
    ON DELETE RESTRICT,
  payment_attempt_id bigint
    REFERENCES ghm.commercial_payment_attempt(id)
    ON DELETE RESTRICT,
  provider_event_id bigint
    REFERENCES ghm.commercial_provider_event(id)
    ON DELETE RESTRICT,
  transaction_kind text NOT NULL DEFAULT 'payment',
  transaction_status text NOT NULL,
  amount_minor_units bigint NOT NULL,
  currency_id bigint NOT NULL
    REFERENCES ghm.currency(id)
    ON DELETE RESTRICT,
  provider_transaction_reference text,
  occurred_at timestamptz NOT NULL,
  recorded_at timestamptz NOT NULL DEFAULT now(),
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,

  CONSTRAINT commercial_payment_transaction_kind_valid
    CHECK (
      transaction_kind IN ('payment', 'refund', 'reversal', 'chargeback')
    ),

  CONSTRAINT commercial_payment_transaction_status_valid
    CHECK (
      transaction_status IN ('pending', 'succeeded', 'failed')
    ),

  CONSTRAINT commercial_payment_transaction_amount_valid
    CHECK (amount_minor_units > 0),

  CONSTRAINT commercial_payment_transaction_provider_reference_valid
    CHECK (
      provider_transaction_reference IS NULL
      OR length(provider_transaction_reference) BETWEEN 1 AND 200
    ),

  CONSTRAINT commercial_payment_transaction_metadata_object
    CHECK (jsonb_typeof(metadata) = 'object')
);

CREATE INDEX commercial_payment_transaction_business_idx
  ON ghm.commercial_payment_transaction (business_id);

CREATE INDEX commercial_payment_transaction_subscription_idx
  ON ghm.commercial_payment_transaction (subscription_id);

CREATE INDEX commercial_payment_transaction_attempt_idx
  ON ghm.commercial_payment_transaction (payment_attempt_id);

CREATE INDEX commercial_payment_transaction_provider_event_idx
  ON ghm.commercial_payment_transaction (provider_event_id);

CREATE INDEX commercial_payment_transaction_occurred_idx
  ON ghm.commercial_payment_transaction (occurred_at);

CREATE TABLE ghm.commercial_event (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id bigint
    REFERENCES ghm.business(id)
    ON DELETE RESTRICT,
  subscription_id bigint
    REFERENCES ghm.commercial_subscription(id)
    ON DELETE RESTRICT,
  event_type text NOT NULL,
  actor_account_id bigint
    REFERENCES ghm.account_identity(id)
    ON DELETE SET NULL,
  source text NOT NULL,
  idempotency_key text,
  payload jsonb NOT NULL DEFAULT '{}'::jsonb,
  occurred_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT commercial_event_type_valid
    CHECK (length(btrim(event_type)) BETWEEN 1 AND 100),

  CONSTRAINT commercial_event_source_valid
    CHECK (length(btrim(source)) BETWEEN 1 AND 100),

  CONSTRAINT commercial_event_idempotency_key_valid
    CHECK (
      idempotency_key IS NULL
      OR length(idempotency_key) BETWEEN 1 AND 200
    ),

  CONSTRAINT commercial_event_payload_object
    CHECK (jsonb_typeof(payload) = 'object')
);

CREATE UNIQUE INDEX commercial_event_idempotency_uq
  ON ghm.commercial_event (idempotency_key)
  WHERE idempotency_key IS NOT NULL;

CREATE INDEX commercial_event_business_idx
  ON ghm.commercial_event (business_id, occurred_at);

CREATE INDEX commercial_event_subscription_idx
  ON ghm.commercial_event (subscription_id, occurred_at);

CREATE TABLE ghm.commercial_founding_allocation (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id bigint NOT NULL UNIQUE
    REFERENCES ghm.business(id)
    ON DELETE RESTRICT,
  subscription_id bigint NOT NULL UNIQUE
    REFERENCES ghm.commercial_subscription(id)
    ON DELETE RESTRICT,
  payment_transaction_id bigint NOT NULL UNIQUE
    REFERENCES ghm.commercial_payment_transaction(id)
    ON DELETE RESTRICT,
  plan_version_id bigint NOT NULL
    REFERENCES ghm.commercial_plan_version(id)
    ON DELETE RESTRICT,
  founding_sequence integer NOT NULL UNIQUE,
  protected_until timestamptz NOT NULL,
  allocated_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT commercial_founding_allocation_sequence_valid
    CHECK (founding_sequence > 0),

  CONSTRAINT commercial_founding_allocation_protected_until_valid
    CHECK (protected_until > allocated_at)
);

CREATE INDEX commercial_founding_allocation_plan_version_idx
  ON ghm.commercial_founding_allocation (plan_version_id);

CREATE INDEX commercial_founding_allocation_protected_until_idx
  ON ghm.commercial_founding_allocation (protected_until);

CREATE OR REPLACE FUNCTION ghm.touch_commercial_plan()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

CREATE TRIGGER commercial_plan_updated_at
BEFORE UPDATE ON ghm.commercial_plan
FOR EACH ROW
EXECUTE FUNCTION ghm.touch_commercial_plan();

CREATE OR REPLACE FUNCTION ghm.touch_commercial_plan_version()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

CREATE TRIGGER commercial_plan_version_updated_at
BEFORE UPDATE ON ghm.commercial_plan_version
FOR EACH ROW
EXECUTE FUNCTION ghm.touch_commercial_plan_version();

CREATE OR REPLACE FUNCTION ghm.touch_commercial_plan_entitlement()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

CREATE TRIGGER commercial_plan_entitlement_updated_at
BEFORE UPDATE ON ghm.commercial_plan_entitlement
FOR EACH ROW
EXECUTE FUNCTION ghm.touch_commercial_plan_entitlement();

CREATE OR REPLACE FUNCTION ghm.touch_commercial_plan_price()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

CREATE TRIGGER commercial_plan_price_updated_at
BEFORE UPDATE ON ghm.commercial_plan_price
FOR EACH ROW
EXECUTE FUNCTION ghm.touch_commercial_plan_price();

CREATE OR REPLACE FUNCTION ghm.touch_commercial_trial()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

CREATE TRIGGER commercial_trial_updated_at
BEFORE UPDATE ON ghm.commercial_trial
FOR EACH ROW
EXECUTE FUNCTION ghm.touch_commercial_trial();

CREATE OR REPLACE FUNCTION ghm.touch_commercial_subscription()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

CREATE TRIGGER commercial_subscription_updated_at
BEFORE UPDATE ON ghm.commercial_subscription
FOR EACH ROW
EXECUTE FUNCTION ghm.touch_commercial_subscription();

CREATE OR REPLACE FUNCTION ghm.touch_commercial_payment_attempt()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

CREATE TRIGGER commercial_payment_attempt_updated_at
BEFORE UPDATE ON ghm.commercial_payment_attempt
FOR EACH ROW
EXECUTE FUNCTION ghm.touch_commercial_payment_attempt();

GRANT USAGE ON SCHEMA ghm TO ghm_runtime;

-- Governed runtime reads.
GRANT SELECT ON
  ghm.commercial_plan,
  ghm.commercial_plan_version,
  ghm.commercial_plan_entitlement,
  ghm.commercial_plan_price,
  ghm.commercial_trial,
  ghm.commercial_subscription
TO ghm_runtime;

-- Payment attempts are created/updated only through the governed
-- Commercial service boundary. No blanket table mutation is granted.
GRANT SELECT ON ghm.commercial_payment_attempt
TO ghm_runtime;

-- Provider events, payment transactions, commercial events, and
-- founding allocations remain internal governed state.
-- No runtime table privileges are granted here.

-- Identity/reference reads required by governed Commercial operations.
GRANT SELECT ON
  ghm.business,
  ghm.account_identity,
  ghm.country,
  ghm.currency
TO ghm_runtime;

-- Sequence access is required only where the governed runtime
-- repository performs identity-backed inserts.
-- Migration authority.
GRANT SELECT, INSERT, UPDATE, DELETE ON
  ghm.commercial_plan,
  ghm.commercial_plan_version,
  ghm.commercial_plan_entitlement,
  ghm.commercial_plan_price,
  ghm.commercial_trial,
  ghm.commercial_subscription,
  ghm.commercial_payment_attempt,
  ghm.commercial_payment_transaction,
  ghm.commercial_provider_event,
  ghm.commercial_event,
  ghm.commercial_founding_allocation
TO ghm_migrator;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA ghm TO ghm_migrator;

