-- Establish the provider-neutral GHM Business Category taxonomy and assignment boundary.
-- Construction-only. No Connect schema mutation or production cutover is authorized.

CREATE TABLE ghm.business_category (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  parent_id uuid REFERENCES ghm.business_category(id) ON DELETE RESTRICT,
  name text NOT NULL,
  slug text NOT NULL,
  description text,
  is_active boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT business_category_slug_unique UNIQUE (slug),
  CONSTRAINT business_category_name_check
    CHECK (char_length(btrim(name)) BETWEEN 1 AND 200),
  CONSTRAINT business_category_slug_check
    CHECK (slug = btrim(slug) AND char_length(slug) BETWEEN 1 AND 200),
  CONSTRAINT business_category_description_check
    CHECK (description IS NULL OR char_length(btrim(description)) BETWEEN 1 AND 2000),
  CONSTRAINT business_category_sort_order_check
    CHECK (sort_order >= 0),
  CONSTRAINT business_category_not_self_parent_check
    CHECK (parent_id IS NULL OR parent_id <> id)
);

CREATE INDEX business_category_parent_idx
  ON ghm.business_category (parent_id);

CREATE INDEX business_category_active_sort_idx
  ON ghm.business_category (is_active, sort_order, name, id);

CREATE TABLE ghm.business_category_assignment (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id bigint NOT NULL
    REFERENCES ghm.business(id) ON DELETE CASCADE,
  category_id uuid NOT NULL
    REFERENCES ghm.business_category(id) ON DELETE RESTRICT,
  is_primary boolean NOT NULL DEFAULT false,
  created_by bigint
    REFERENCES ghm.account_identity(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT business_category_assignment_unique
    UNIQUE (business_id, category_id)
);

CREATE UNIQUE INDEX business_category_assignment_one_primary_idx
  ON ghm.business_category_assignment (business_id)
  WHERE is_primary = true;

CREATE INDEX business_category_assignment_business_idx
  ON ghm.business_category_assignment (business_id, is_primary, created_at, id);

CREATE INDEX business_category_assignment_category_idx
  ON ghm.business_category_assignment (category_id, business_id);

ALTER TABLE ghm.business_category OWNER TO ghm_schema_owner;
ALTER TABLE ghm.business_category_assignment OWNER TO ghm_schema_owner;


GRANT USAGE ON SCHEMA ghm TO ghm_runtime;

GRANT SELECT ON TABLE ghm.business_category TO ghm_runtime;
GRANT SELECT ON TABLE ghm.business_category_assignment TO ghm_runtime;

GRANT INSERT (
  business_id,
  category_id,
  is_primary,
  created_by
) ON TABLE ghm.business_category_assignment TO ghm_runtime;

GRANT UPDATE (is_primary)
  ON TABLE ghm.business_category_assignment
  TO ghm_runtime;

GRANT USAGE, SELECT
  ON SEQUENCE ghm.business_category_assignment_id_seq
  TO ghm_runtime;

-- Runtime DELETE is deliberately not granted.
