-- Construct the provider-neutral GHM Saved Business relationship.
-- Construction-only. No production migration or product cutover is authorized.

CREATE TABLE ghm.saved_business (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  account_id bigint NOT NULL
    REFERENCES ghm.account_identity(id)
    ON DELETE CASCADE,

  business_id bigint NOT NULL
    REFERENCES ghm.business(id)
    ON DELETE CASCADE,

  created_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT saved_business_account_business_unique
    UNIQUE (account_id, business_id)
);

CREATE INDEX saved_business_account_created_idx
  ON ghm.saved_business (account_id, created_at DESC, id);

CREATE INDEX saved_business_business_idx
  ON ghm.saved_business (business_id, id);

ALTER TABLE ghm.saved_business OWNER TO ghm_schema_owner;

GRANT USAGE ON SCHEMA ghm TO ghm_runtime;

GRANT SELECT
  ON TABLE ghm.saved_business
  TO ghm_runtime;

GRANT INSERT (
  account_id,
  business_id
)
  ON TABLE ghm.saved_business
  TO ghm_runtime;

GRANT DELETE
  ON TABLE ghm.saved_business
  TO ghm_runtime;

GRANT USAGE
  ON SEQUENCE ghm.saved_business_id_seq
  TO ghm_runtime;
