-- QuoteFlow Customer capability, reconciled into the provider-neutral GHM model.
-- Construction-only migration; production cutover is not part of this change.

CREATE TABLE ghm.customer (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id bigint NOT NULL
    REFERENCES ghm.account_identity(id)
    ON DELETE CASCADE,
  name text NOT NULL,
  phone text,
  email text,
  status text NOT NULL DEFAULT 'active',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT customer_name_nonblank_ck
    CHECK (char_length(btrim(name)) > 0),
  CONSTRAINT customer_status_ck
    CHECK (status IN ('active', 'archived'))
);

CREATE INDEX customer_account_created_idx
  ON ghm.customer (account_id, created_at DESC);

CREATE INDEX customer_account_status_created_idx
  ON ghm.customer (account_id, status, created_at DESC);

GRANT USAGE ON SCHEMA ghm TO ghm_runtime;

GRANT SELECT
  ON TABLE ghm.customer
  TO ghm_runtime;

GRANT INSERT (
  account_id,
  name,
  phone,
  email
)
  ON TABLE ghm.customer
  TO ghm_runtime;

GRANT UPDATE (
  status,
  updated_at
)
  ON TABLE ghm.customer
  TO ghm_runtime;

GRANT USAGE
  ON SEQUENCE ghm.customer_id_seq
  TO ghm_runtime;

ALTER DEFAULT PRIVILEGES FOR ROLE ghm_schema_owner IN SCHEMA ghm
  GRANT USAGE ON SEQUENCES TO ghm_runtime;

-- No DELETE privilege is granted to ghm_runtime.
-- No blanket table DML or contact-field mutation privilege is granted.
