CREATE TABLE ghm.opportunity_type (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code text NOT NULL,
  name text NOT NULL,
  description text,
  version integer NOT NULL DEFAULT 1,
  is_active boolean NOT NULL DEFAULT true,
  sort_order integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT opportunity_type_code_valid CHECK (code = lower(code) AND code ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$'),
  CONSTRAINT opportunity_type_name_valid CHECK (length(btrim(name)) BETWEEN 1 AND 120),
  CONSTRAINT opportunity_type_description_valid CHECK (description IS NULL OR length(btrim(description)) BETWEEN 1 AND 2000),
  CONSTRAINT opportunity_type_version_valid CHECK (version >= 1),
  CONSTRAINT opportunity_type_sort_order_valid CHECK (sort_order >= 0),
  CONSTRAINT opportunity_type_code_version_unique UNIQUE (code, version)
);

CREATE INDEX opportunity_type_active_sort_idx ON ghm.opportunity_type (is_active, sort_order, name);

CREATE TABLE ghm.country (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code text NOT NULL UNIQUE,
  name text NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  CONSTRAINT country_code_valid CHECK (code = upper(code) AND code ~ '^[A-Z]{2}$'),
  CONSTRAINT country_name_valid CHECK (length(btrim(name)) BETWEEN 1 AND 120)
);

CREATE TABLE ghm.currency (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code text NOT NULL UNIQUE,
  name text NOT NULL,
  symbol text,
  is_active boolean NOT NULL DEFAULT true,
  CONSTRAINT currency_code_valid CHECK (code = upper(code) AND code ~ '^[A-Z]{3}$'),
  CONSTRAINT currency_name_valid CHECK (length(btrim(name)) BETWEEN 1 AND 120)
);

INSERT INTO ghm.opportunity_type (code, name, description, sort_order) VALUES
  ('service-request', 'Service Request', 'A request for a Business or professional service.', 10),
  ('supply-request', 'Supply Request', 'A request for products, materials, equipment, or other supplied goods.', 20),
  ('procurement', 'Procurement', 'A governed commercial sourcing or procurement requirement.', 30),
  ('tender', 'Tender', 'A formal competitive commercial request or tender.', 40),
  ('partnership', 'Partnership', 'A proposed strategic, delivery, channel, or commercial partnership.', 50),
  ('consulting', 'Consulting', 'A consulting, advisory, or specialist professional engagement.', 60),
  ('manufacturing', 'Manufacturing', 'A manufacturing, fabrication, production, or assembly requirement.', 70),
  ('distribution', 'Distribution', 'A distribution, reseller, logistics, or channel opportunity.', 80),
  ('employment', 'Employment', 'An employment, contracting, or talent engagement opportunity.', 90),
  ('investment', 'Investment', 'An investment, funding, or capital participation opportunity.', 100),
  ('project', 'Project', 'A project-based commercial opportunity with project-specific workflow.', 110);

CREATE TABLE ghm.opportunity (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  opportunity_type_id bigint NOT NULL REFERENCES ghm.opportunity_type(id) ON DELETE RESTRICT,
  creator_account_id bigint NOT NULL REFERENCES ghm.account_identity(id) ON DELETE RESTRICT,
  owner_business_id bigint REFERENCES ghm.business(id) ON DELETE RESTRICT,
  country_id bigint REFERENCES ghm.country(id) ON DELETE RESTRICT,
  currency_id bigint REFERENCES ghm.currency(id) ON DELETE RESTRICT,
  title text NOT NULL,
  description text NOT NULL,
  lifecycle_status text NOT NULL DEFAULT 'draft',
  visibility text NOT NULL DEFAULT 'private',
  budget_min numeric(14,2),
  budget_max numeric(14,2),
  opens_at timestamptz,
  closes_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT opportunity_title_valid CHECK (length(btrim(title)) BETWEEN 1 AND 200),
  CONSTRAINT opportunity_description_valid CHECK (length(btrim(description)) BETWEEN 1 AND 10000),
  CONSTRAINT opportunity_lifecycle_valid CHECK (lifecycle_status IN ('draft','open','responding','evaluating','awarded','in_progress','completed','cancelled','archived')),
  CONSTRAINT opportunity_visibility_valid CHECK (visibility IN ('private','participants','authenticated','public')),
  CONSTRAINT opportunity_budget_min_valid CHECK (budget_min IS NULL OR budget_min >= 0),
  CONSTRAINT opportunity_budget_max_valid CHECK (budget_max IS NULL OR budget_max >= 0),
  CONSTRAINT opportunity_budget_range_valid CHECK (budget_min IS NULL OR budget_max IS NULL OR budget_max >= budget_min),
  CONSTRAINT opportunity_open_close_valid CHECK (opens_at IS NULL OR closes_at IS NULL OR closes_at >= opens_at),
  CONSTRAINT opportunity_public_not_draft CHECK (visibility <> 'public' OR lifecycle_status <> 'draft')
);

CREATE INDEX opportunity_type_status_created_idx ON ghm.opportunity (opportunity_type_id, lifecycle_status, created_at DESC);
CREATE INDEX opportunity_creator_created_idx ON ghm.opportunity (creator_account_id, created_at DESC);
CREATE INDEX opportunity_owner_business_created_idx ON ghm.opportunity (owner_business_id, created_at DESC) WHERE owner_business_id IS NOT NULL;
CREATE INDEX opportunity_visibility_status_created_idx ON ghm.opportunity (visibility, lifecycle_status, created_at DESC);
CREATE INDEX opportunity_country_status_created_idx ON ghm.opportunity (country_id, lifecycle_status, created_at DESC) WHERE country_id IS NOT NULL;

GRANT USAGE ON SCHEMA ghm TO ghm_runtime;
GRANT SELECT, INSERT, UPDATE ON ghm.opportunity TO ghm_runtime;
GRANT SELECT ON ghm.opportunity_type, ghm.country, ghm.currency TO ghm_runtime;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA ghm TO ghm_runtime;

GRANT SELECT, INSERT, UPDATE, DELETE ON ghm.opportunity, ghm.opportunity_type, ghm.country, ghm.currency TO ghm_migrator;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA ghm TO ghm_migrator;
