begin;

create table ghm.currency (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  symbol text not null,
  minor_unit integer not null default 2,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint currency_code_format
    check (code ~ '^[A-Z]{3}$'),
  constraint currency_name_not_blank
    check (btrim(name) <> ''),
  constraint currency_symbol_not_blank
    check (btrim(symbol) <> ''),
  constraint currency_minor_unit_range
    check (minor_unit between 0 and 6)
);

create table ghm.country (
  id bigint generated by default as identity primary key,
  code_alpha2 text not null unique,
  code_alpha3 text not null unique,
  name text not null,
  default_currency_id bigint
    references ghm.currency(id)
    on delete restrict,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint country_alpha2_code_format
    check (code_alpha2 ~ '^[A-Z]{2}$'),
  constraint country_alpha3_code_format
    check (code_alpha3 ~ '^[A-Z]{3}$'),
  constraint country_name_not_blank
    check (btrim(name) <> '')
);

create index country_default_currency_id_idx
  on ghm.country(default_currency_id);

create or replace function ghm.set_currency_updated_at()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, ghm
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

alter function ghm.set_currency_updated_at() owner to ghm_schema_owner;
revoke all on function ghm.set_currency_updated_at() from public;

create or replace function ghm.set_country_updated_at()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, ghm
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

alter function ghm.set_country_updated_at() owner to ghm_schema_owner;
revoke all on function ghm.set_country_updated_at() from public;

create trigger currency_set_updated_at
before update on ghm.currency
for each row
execute function ghm.set_currency_updated_at();

create trigger country_set_updated_at
before update on ghm.country
for each row
execute function ghm.set_country_updated_at();

alter table ghm.currency owner to ghm_schema_owner;
alter table ghm.country owner to ghm_schema_owner;

comment on table ghm.currency is
  'Canonical GHM currency reference identity used by governed resources.';

comment on table ghm.country is
  'Canonical GHM country reference identity used by governed resources.';

insert into ghm.currency (
  code,
  name,
  symbol,
  minor_unit
)
values (
  'ZAR',
  'South African Rand',
  'R',
  2
);

insert into ghm.country (
  code_alpha2,
  code_alpha3,
  name,
  default_currency_id
)
select
  'ZA',
  'ZAF',
  'South Africa',
  id
from ghm.currency
where code = 'ZAR';

grant usage on schema ghm to ghm_runtime;

grant select on table ghm.currency, ghm.country to ghm_runtime;

revoke insert, update, delete, truncate, references, trigger
  on table ghm.currency, ghm.country
  from ghm_runtime;

grant usage, select on sequence ghm.currency_id_seq, ghm.country_id_seq
  to ghm_runtime;

commit;
