CREATE TABLE account_identity (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name text,
  phone text,
  avatar_ref text,
  role text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT account_identity_role_check
    CHECK (role IN ('admin', 'customer', 'business'))
);

CREATE TABLE business (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  slug text NOT NULL,
  verification_status text NOT NULL DEFAULT 'pending',
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT business_verification_status_check
    CHECK (verification_status IN ('pending', 'approved', 'rejected')),
  CONSTRAINT business_name_nonblank_check
    CHECK (btrim(name) <> ''),
  CONSTRAINT business_slug_nonblank_check
    CHECK (btrim(slug) <> ''),
  CONSTRAINT business_slug_unique UNIQUE (slug)
);

CREATE TABLE business_membership (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id bigint NOT NULL REFERENCES business(id) ON DELETE CASCADE,
  account_id bigint NOT NULL REFERENCES account_identity(id) ON DELETE CASCADE,
  membership_role text NOT NULL,
  membership_status text NOT NULL DEFAULT 'active',
  created_by bigint REFERENCES account_identity(id) ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT business_membership_role_check
    CHECK (membership_role IN ('owner', 'administrator', 'member')),
  CONSTRAINT business_membership_status_check
    CHECK (membership_status IN ('active', 'inactive', 'revoked')),
  CONSTRAINT business_membership_business_account_unique
    UNIQUE (business_id, account_id)
);

CREATE UNIQUE INDEX business_membership_one_active_owner_idx
  ON business_membership (business_id)
  WHERE membership_role = 'owner' AND membership_status = 'active';

CREATE INDEX business_membership_account_active_idx
  ON business_membership (account_id, membership_status, created_at, id);

CREATE INDEX business_membership_business_status_idx
  ON business_membership (business_id, membership_status, membership_role, id);
