BEGIN;

CREATE TABLE ghm.review (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id bigint NOT NULL REFERENCES ghm.business(id) ON DELETE CASCADE,
  reviewer_id bigint NOT NULL REFERENCES ghm.account_identity(id) ON DELETE CASCADE,
  reviewer_name text NOT NULL,
  rating smallint NOT NULL,
  title text NOT NULL,
  body text NOT NULL,
  moderation_status text NOT NULL DEFAULT 'pending',
  moderation_reason text,
  moderated_by bigint REFERENCES ghm.account_identity(id) ON DELETE SET NULL,
  moderated_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT review_rating_check
    CHECK (rating BETWEEN 1 AND 5),
  CONSTRAINT review_reviewer_name_check
    CHECK (char_length(btrim(reviewer_name)) BETWEEN 1 AND 160),
  CONSTRAINT review_title_check
    CHECK (char_length(btrim(title)) BETWEEN 3 AND 120),
  CONSTRAINT review_body_check
    CHECK (char_length(btrim(body)) BETWEEN 10 AND 2000),
  CONSTRAINT review_moderation_status_check
    CHECK (moderation_status IN ('pending', 'approved', 'rejected')),
  CONSTRAINT review_moderation_state_check
    CHECK (
      (moderation_status = 'pending'
        AND moderated_by IS NULL
        AND moderated_at IS NULL
        AND moderation_reason IS NULL)
      OR
      (moderation_status = 'approved'
        AND moderated_by IS NOT NULL
        AND moderated_at IS NOT NULL
        AND moderation_reason IS NULL)
      OR
      (moderation_status = 'rejected'
        AND moderated_by IS NOT NULL
        AND moderated_at IS NOT NULL
        AND char_length(btrim(COALESCE(moderation_reason, ''))) > 0)
    ),
  CONSTRAINT review_business_reviewer_unique
    UNIQUE (business_id, reviewer_id)
);

CREATE INDEX review_business_created_at_idx
  ON ghm.review (business_id, created_at DESC);

CREATE INDEX review_reviewer_created_at_idx
  ON ghm.review (reviewer_id, created_at DESC);

CREATE INDEX review_approved_business_created_at_idx
  ON ghm.review (business_id, created_at DESC)
  WHERE moderation_status = 'approved';

CREATE INDEX review_pending_created_at_idx
  ON ghm.review (created_at ASC)
  WHERE moderation_status = 'pending';

COMMENT ON TABLE ghm.review IS
  'Canonical customer-to-Business Review capability reconciled from Zaid Connect; public visibility requires approved moderation and eligible Business state.';

COMMENT ON COLUMN ghm.review.reviewer_name IS
  'Submission-time reviewer display-name snapshot; not an authorization principal.';

COMMENT ON COLUMN ghm.review.rating IS
  'Customer rating from 1 through 5.';

COMMENT ON COLUMN ghm.review.moderation_status IS
  'Governed moderation lifecycle: pending, approved, rejected.';

COMMENT ON COLUMN ghm.review.moderation_reason IS
  'Required only for rejected Reviews; must remain null for pending and approved Reviews.';

COMMENT ON COLUMN ghm.review.moderated_by IS
  'Canonical GHM administrator identity that performed the moderation decision.';

COMMENT ON COLUMN ghm.review.moderated_at IS
  'Timestamp of the moderation decision.';

COMMIT;
