-- Establish the provider-neutral GHM Opportunity Participation relation.
-- Construction-only. No production migration or product cutover is authorized.
-- Contract: docs/architecture/OPPORTUNITY_PARTICIPATION_SCHEMA_CONTRACT.md
-- Operation boundary: docs/architecture/OPPORTUNITY_PARTICIPATION_OPERATION_CONTRACT.md

CREATE TABLE ghm.opportunity_participant (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  opportunity_id bigint NOT NULL
    REFERENCES ghm.opportunity(id)
    ON DELETE CASCADE,

  account_id bigint
    REFERENCES ghm.account_identity(id)
    ON DELETE CASCADE,

  business_id bigint
    REFERENCES ghm.business(id)
    ON DELETE CASCADE,

  participation_role text NOT NULL,
  participation_status text NOT NULL DEFAULT 'active',

  created_by bigint NOT NULL
    REFERENCES ghm.account_identity(id)
    ON DELETE RESTRICT,

  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT opportunity_participant_principal_xor_ck
    CHECK (
      (account_id IS NOT NULL AND business_id IS NULL)
      OR
      (account_id IS NULL AND business_id IS NOT NULL)
    ),

  CONSTRAINT opportunity_participant_role_ck
    CHECK (
      participation_role IN (
        'creator',
        'owner',
        'recipient',
        'responder',
        'evaluator',
        'fulfiller'
      )
    ),

  CONSTRAINT opportunity_participant_status_ck
    CHECK (
      participation_status IN (
        'invited',
        'active',
        'declined',
        'withdrawn',
        'removed',
        'completed'
      )
    )
);

CREATE UNIQUE INDEX opportunity_participant_opportunity_account_role_uq
  ON ghm.opportunity_participant (
    opportunity_id,
    account_id,
    participation_role
  )
  WHERE account_id IS NOT NULL;

CREATE UNIQUE INDEX opportunity_participant_opportunity_business_role_uq
  ON ghm.opportunity_participant (
    opportunity_id,
    business_id,
    participation_role
  )
  WHERE business_id IS NOT NULL;

CREATE INDEX opportunity_participant_account_status_created_idx
  ON ghm.opportunity_participant (
    account_id,
    participation_status,
    created_at DESC
  )
  WHERE account_id IS NOT NULL;

CREATE INDEX opportunity_participant_business_status_created_idx
  ON ghm.opportunity_participant (
    business_id,
    participation_status,
    created_at DESC
  )
  WHERE business_id IS NOT NULL;

CREATE INDEX opportunity_participant_opportunity_role_status_idx
  ON ghm.opportunity_participant (
    opportunity_id,
    participation_role,
    participation_status
  );

CREATE OR REPLACE FUNCTION ghm.touch_opportunity_participant()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

CREATE TRIGGER opportunity_participant_updated_at
BEFORE UPDATE ON ghm.opportunity_participant
FOR EACH ROW
EXECUTE FUNCTION ghm.touch_opportunity_participant();

GRANT USAGE ON SCHEMA ghm TO ghm_runtime;

GRANT SELECT
  ON TABLE ghm.opportunity_participant
  TO ghm_runtime;

-- Runtime INSERT is restricted to fields required by governed service
-- operations. id and timestamps remain database-generated; created_by is
-- supplied only from the authenticated service context, never from provider
-- identity fields.
GRANT INSERT (
  opportunity_id,
  account_id,
  business_id,
  participation_role,
  participation_status,
  created_by
)
  ON TABLE ghm.opportunity_participant
  TO ghm_runtime;

GRANT USAGE
  ON SEQUENCE ghm.opportunity_participant_id_seq
  TO ghm_runtime;

ALTER DEFAULT PRIVILEGES FOR ROLE ghm_schema_owner IN SCHEMA ghm
  GRANT USAGE ON SEQUENCES TO ghm_runtime;

-- Participant role/status updates remain service-contract gated and are not
-- granted to runtime until a concrete transition authority is separately
-- specified and qualified. No runtime DELETE privilege is granted.

GRANT SELECT, INSERT, UPDATE, DELETE
  ON TABLE ghm.opportunity_participant
  TO ghm_migrator;

GRANT USAGE, SELECT
  ON SEQUENCE ghm.opportunity_participant_id_seq
  TO ghm_migrator;
