-- Construct the provider-neutral GHM Saved Business relationship.
-- Construction-only. No production migration or product cutover is authorized.

CREATE TABLE ghm.saved_business (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  account_id bigint NOT NULL
    REFERENCES ghm.account_identity(id)
    ON DELETE CASCADE,

  business_id bigint NOT NULL
    REFERENCES ghm.business(id)
    ON DELETE CASCADE,

  created_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT saved_business_account_business_unique
    UNIQUE (account_id, business_id)
);

CREATE INDEX saved_business_account_created_idx
  ON ghm.saved_business (account_id, created_at DESC, id);

CREATE INDEX saved_business_business_idx
  ON ghm.saved_business (business_id, id);

ALTER TABLE ghm.saved_business OWNER TO ghm_schema_owner;

GRANT USAGE ON SCHEMA ghm TO ghm_runtime;

GRANT SELECT
  ON TABLE ghm.saved_business
  TO ghm_runtime;

GRANT INSERT (
  account_id,
  business_id
)
  ON TABLE ghm.saved_business
  TO ghm_runtime;

REVOKE DELETE, UPDATE
  ON TABLE ghm.saved_business
  FROM ghm_runtime;

GRANT USAGE
  ON SEQUENCE ghm.saved_business_id_seq
  TO ghm_runtime;

CREATE OR REPLACE FUNCTION ghm.delete_saved_business(p_account_id bigint, p_saved_business_id bigint)
RETURNS boolean
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, ghm
AS $$
DECLARE
  deleted_count integer;
BEGIN
  IF p_account_id IS NULL OR p_account_id <= 0 THEN
    RAISE EXCEPTION 'Account ID must be a positive integer';
  END IF;

  IF p_saved_business_id IS NULL OR p_saved_business_id <= 0 THEN
    RAISE EXCEPTION 'Saved Business ID must be a positive integer';
  END IF;

  DELETE FROM ghm.saved_business
   WHERE id = p_saved_business_id
     AND account_id = p_account_id;

  GET DIAGNOSTICS deleted_count = ROW_COUNT;
  RETURN deleted_count = 1;
END;
$$;

ALTER FUNCTION ghm.delete_saved_business(bigint, bigint) OWNER TO ghm_schema_owner;
REVOKE ALL ON FUNCTION ghm.delete_saved_business(bigint, bigint) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION ghm.delete_saved_business(bigint, bigint) TO ghm_runtime;
