-- Establish the separate governed Support Request conversation relation.
-- Construction-only migration; production cutover is not part of this change.

CREATE TABLE ghm.support_request_message (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  support_request_id bigint NOT NULL
    REFERENCES ghm.support_request(id)
    ON DELETE CASCADE,
  account_id bigint NOT NULL
    REFERENCES ghm.account_identity(id)
    ON DELETE RESTRICT,
  sender_kind text NOT NULL,
  body text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT support_request_message_sender_kind_check
    CHECK (sender_kind IN ('customer', 'admin')),
  CONSTRAINT support_request_message_body_length_check
    CHECK (char_length(btrim(body)) BETWEEN 1 AND 4000)
);

CREATE INDEX support_request_message_request_created_idx
  ON ghm.support_request_message (support_request_id, created_at ASC, id ASC);

CREATE INDEX support_request_message_account_created_idx
  ON ghm.support_request_message (account_id, created_at DESC, id DESC);

ALTER TABLE ghm.support_request_message OWNER TO ghm_schema_owner;

GRANT USAGE ON SCHEMA ghm TO ghm_runtime;

GRANT SELECT
  ON TABLE ghm.support_request_message
  TO ghm_runtime;

-- Message creation is deliberately narrow. The service will derive the
-- authenticated account and trusted sender kind; callers do not receive
-- privilege to mutate existing messages.
GRANT INSERT (
  support_request_id,
  account_id,
  sender_kind,
  body
)
  ON TABLE ghm.support_request_message
  TO ghm_runtime;

GRANT USAGE
  ON SEQUENCE ghm.support_request_message_id_seq
  TO ghm_runtime;

-- No UPDATE privilege is granted.
-- No DELETE privilege is granted.
