-- Establish the first governed GHM Support Request relation.
-- Construction-only migration; production cutover is not part of this change.
-- The request is customer-owned. Business association is optional and
-- authorization remains an explicit repository/service responsibility.

CREATE TABLE ghm.support_request (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id bigint NOT NULL
    REFERENCES ghm.account_identity(id)
    ON DELETE CASCADE,
  business_id bigint
    REFERENCES ghm.business(id)
    ON DELETE SET NULL,
  category text NOT NULL,
  subject text NOT NULL,
  description text NOT NULL,
  priority text NOT NULL DEFAULT 'normal',
  status text NOT NULL DEFAULT 'open',
  resolution_summary text,
  resolved_at timestamptz,
  closed_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT support_request_category_check
    CHECK (category IN (
      'account',
      'business',
      'directory',
      'marketplace',
      'workspace',
      'trial_and_commercial',
      'technical',
      'other'
    )),
  CONSTRAINT support_request_subject_length_check
    CHECK (char_length(btrim(subject)) BETWEEN 3 AND 160),
  CONSTRAINT support_request_description_length_check
    CHECK (char_length(btrim(description)) BETWEEN 10 AND 4000),
  CONSTRAINT support_request_priority_check
    CHECK (priority IN ('low', 'normal', 'high', 'urgent')),
  CONSTRAINT support_request_status_check
    CHECK (status IN ('open', 'in_progress', 'resolved', 'closed')),
  CONSTRAINT support_request_resolution_length_check
    CHECK (
      resolution_summary IS NULL
      OR char_length(btrim(resolution_summary)) BETWEEN 1 AND 2000
    ),
  CONSTRAINT support_request_closed_requires_resolved_check
    CHECK (closed_at IS NULL OR resolved_at IS NOT NULL)
);

CREATE INDEX support_request_account_created_idx
  ON ghm.support_request (account_id, created_at DESC, id DESC);

CREATE INDEX support_request_business_created_idx
  ON ghm.support_request (business_id, created_at DESC, id DESC)
  WHERE business_id IS NOT NULL;

CREATE INDEX support_request_status_created_idx
  ON ghm.support_request (status, created_at DESC, id DESC);

ALTER TABLE ghm.support_request OWNER TO ghm_schema_owner;

GRANT USAGE ON SCHEMA ghm TO ghm_runtime;

GRANT SELECT
  ON TABLE ghm.support_request
  TO ghm_runtime;

-- Runtime creation is intentionally narrow. Identity, status, priority,
-- resolution state, and timestamps are server-controlled.
GRANT INSERT (
  account_id,
  business_id,
  category,
  subject,
  description
)
  ON TABLE ghm.support_request
  TO ghm_runtime;

-- Lifecycle mutation is explicit and column-scoped. Authorization remains
-- inside the service/repository; arbitrary business/account mutation is not
-- exposed to the runtime role.
GRANT UPDATE (
  status,
  resolution_summary,
  resolved_at,
  closed_at,
  updated_at
)
  ON TABLE ghm.support_request
  TO ghm_runtime;

GRANT USAGE
  ON SEQUENCE ghm.support_request_id_seq
  TO ghm_runtime;

-- No DELETE privilege is granted to ghm_runtime.
-- No blanket table DML or arbitrary sequence privilege is granted.
