CREATE TABLE ghm.opportunity_capability_requirement (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  opportunity_id bigint NOT NULL
    REFERENCES ghm.opportunity(id)
    ON DELETE CASCADE,

  capability_id uuid NOT NULL
    REFERENCES ghm.capability(id)
    ON DELETE RESTRICT,

  importance text NOT NULL DEFAULT 'required',

  minimum_proficiency_level text,

  description text,

  sort_order integer NOT NULL DEFAULT 0,

  created_by bigint NOT NULL
    REFERENCES ghm.account_identity(id)
    ON DELETE RESTRICT,

  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT opportunity_capability_requirement_importance_valid
    CHECK (importance IN ('required', 'preferred')),

  CONSTRAINT opportunity_capability_requirement_proficiency_valid
    CHECK (
      minimum_proficiency_level IS NULL
      OR minimum_proficiency_level IN (
        'foundational',
        'proficient',
        'advanced',
        'expert'
      )
    ),

  CONSTRAINT opportunity_capability_requirement_description_valid
    CHECK (
      description IS NULL
      OR length(btrim(description)) BETWEEN 1 AND 1000
    ),

  CONSTRAINT opportunity_capability_requirement_sort_order_valid
    CHECK (sort_order BETWEEN 0 AND 1000),

  CONSTRAINT opportunity_capability_requirement_unique_capability
    UNIQUE (opportunity_id, capability_id)
);

CREATE INDEX opportunity_capability_requirement_opportunity_idx
  ON ghm.opportunity_capability_requirement (
    opportunity_id,
    sort_order,
    id
  );

CREATE INDEX opportunity_capability_requirement_capability_idx
  ON ghm.opportunity_capability_requirement (
    capability_id,
    importance
  );

CREATE OR REPLACE FUNCTION ghm.touch_opportunity_capability_requirement()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

CREATE TRIGGER opportunity_capability_requirement_updated_at
BEFORE UPDATE ON ghm.opportunity_capability_requirement
FOR EACH ROW
EXECUTE FUNCTION ghm.touch_opportunity_capability_requirement();

GRANT USAGE ON SCHEMA ghm TO ghm_runtime;

GRANT SELECT ON TABLE ghm.opportunity_capability_requirement
  TO ghm_runtime;

GRANT INSERT (
  opportunity_id,
  capability_id,
  importance,
  minimum_proficiency_level,
  description,
  sort_order,
  created_by
) ON TABLE ghm.opportunity_capability_requirement
  TO ghm_runtime;

GRANT DELETE ON TABLE ghm.opportunity_capability_requirement
  TO ghm_runtime;

GRANT USAGE ON SEQUENCE ghm.opportunity_capability_requirement_id_seq
  TO ghm_runtime;

ALTER DEFAULT PRIVILEGES FOR ROLE ghm_schema_owner IN SCHEMA ghm
  GRANT USAGE ON SEQUENCES TO ghm_runtime;

-- No blanket UPDATE privilege.
-- No blanket ALL privilege.
-- Replacement is authorized by the application repository/service layer.
-- DELETE is limited to this child-resource table because replacement semantics
-- require removal of the opportunity's existing requirement set.
