-- Provider-neutral Business Hours relation reconciled from live Zaid Connect.
-- Construction-only. No production cutover is authorized.

CREATE TABLE ghm.business_hours (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id bigint NOT NULL
    REFERENCES ghm.business(id)
    ON DELETE CASCADE,
  day_of_week smallint NOT NULL,
  is_closed boolean NOT NULL DEFAULT false,
  open_time time,
  close_time time,
  created_by bigint
    REFERENCES ghm.account_identity(id)
    ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT business_hours_day_check
    CHECK (day_of_week BETWEEN 0 AND 6),
  CONSTRAINT business_hours_time_state_check
    CHECK (
      (is_closed AND open_time IS NULL AND close_time IS NULL)
      OR
      (
        NOT is_closed
        AND open_time IS NOT NULL
        AND close_time IS NOT NULL
        AND close_time > open_time
      )
    ),
  CONSTRAINT business_hours_business_day_unique
    UNIQUE (business_id, day_of_week)
);

CREATE INDEX business_hours_business_day_idx
  ON ghm.business_hours (business_id, day_of_week);

ALTER TABLE ghm.business_hours OWNER TO ghm_schema_owner;

GRANT USAGE ON SCHEMA ghm TO ghm_runtime;
GRANT SELECT ON TABLE ghm.business_hours TO ghm_runtime;
GRANT USAGE ON SEQUENCE ghm.business_hours_id_seq TO ghm_runtime;

-- Runtime mutation is exposed only through this governed replacement function.
CREATE OR REPLACE FUNCTION ghm.replace_business_hours(
  p_business_id bigint,
  p_account_id bigint,
  p_hours jsonb
)
RETURNS SETOF ghm.business_hours
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = ghm, pg_catalog
AS $$
BEGIN
  IF p_business_id IS NULL OR p_business_id <= 0 THEN
    RAISE EXCEPTION 'Business identifier is required';
  END IF;

  IF p_account_id IS NULL OR p_account_id <= 0 THEN
    RAISE EXCEPTION 'Authenticated account is required';
  END IF;

  IF p_hours IS NULL OR jsonb_typeof(p_hours) <> 'array' THEN
    RAISE EXCEPTION 'Business Hours must be a JSON array';
  END IF;

  IF jsonb_array_length(p_hours) > 7 THEN
    RAISE EXCEPTION 'A maximum of seven Business Hours records is allowed';
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM ghm.business b
    JOIN ghm.business_membership bm
      ON bm.business_id = b.id
     AND bm.account_id = p_account_id
     AND bm.membership_status = 'active'
     AND bm.membership_role IN ('owner', 'administrator')
    WHERE b.id = p_business_id
      AND b.is_active = true
  ) THEN
    RAISE EXCEPTION 'Business management permission required';
  END IF;

  IF EXISTS (
    SELECT 1
    FROM jsonb_array_elements(p_hours) item
    WHERE jsonb_typeof(item) <> 'object'
       OR coalesce(item->>'day_of_week', '') !~ '^[0-6]$'
       OR coalesce(item->>'is_closed', 'false') NOT IN ('true', 'false')
       OR (
         coalesce((item->>'is_closed')::boolean, false)
         AND (
           nullif(item->>'open_time', '') IS NOT NULL
           OR nullif(item->>'close_time', '') IS NOT NULL
         )
       )
       OR (
         NOT coalesce((item->>'is_closed')::boolean, false)
         AND (
           nullif(item->>'open_time', '') IS NULL
           OR nullif(item->>'close_time', '') IS NULL
           OR (item->>'open_time')::time >= (item->>'close_time')::time
         )
       )
  ) THEN
    RAISE EXCEPTION 'One or more Business Hours records are invalid';
  END IF;

  IF (
    SELECT count(*) - count(DISTINCT (item->>'day_of_week')::smallint)
    FROM jsonb_array_elements(p_hours) item
  ) > 0 THEN
    RAISE EXCEPTION 'Duplicate Business Hours days are not allowed';
  END IF;

  DELETE FROM ghm.business_hours
  WHERE business_id = p_business_id;

  INSERT INTO ghm.business_hours (
    business_id,
    day_of_week,
    is_closed,
    open_time,
    close_time,
    created_by
  )
  SELECT
    p_business_id,
    (item->>'day_of_week')::smallint,
    coalesce((item->>'is_closed')::boolean, false),
    nullif(item->>'open_time', '')::time,
    nullif(item->>'close_time', '')::time,
    p_account_id
  FROM jsonb_array_elements(p_hours) item;

  RETURN QUERY
  SELECT *
  FROM ghm.business_hours
  WHERE business_id = p_business_id
  ORDER BY day_of_week, id;
END;
$$;

ALTER FUNCTION ghm.replace_business_hours(bigint, bigint, jsonb)
  OWNER TO ghm_schema_owner;

REVOKE ALL ON FUNCTION ghm.replace_business_hours(bigint, bigint, jsonb) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION ghm.replace_business_hours(bigint, bigint, jsonb) TO ghm_runtime;

-- No runtime INSERT, UPDATE, or DELETE table privilege is granted.
