BEGIN;

CREATE TABLE ghm.storage_object (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tenant_business_id bigint NOT NULL REFERENCES ghm.business(id) ON DELETE CASCADE,
  resource_type text NOT NULL,
  resource_id bigint NOT NULL,
  object_class text NOT NULL,
  provider_key text NOT NULL,
  content_type text NOT NULL,
  byte_size bigint NOT NULL,
  checksum text,
  visibility text NOT NULL,
  status text NOT NULL DEFAULT 'pending',
  original_filename text,
  created_at timestamptz NOT NULL DEFAULT clock_timestamp(),
  available_at timestamptz,
  deleted_at timestamptz,

  CONSTRAINT storage_object_provider_key_unique UNIQUE (provider_key),
  CONSTRAINT storage_object_byte_size_check CHECK (byte_size >= 0),
  CONSTRAINT storage_object_content_type_nonblank_check CHECK (btrim(content_type) <> ''),
  CONSTRAINT storage_object_resource_type_nonblank_check CHECK (btrim(resource_type) <> ''),
  CONSTRAINT storage_object_object_class_nonblank_check CHECK (btrim(object_class) <> ''),
  CONSTRAINT storage_object_visibility_check CHECK (
    visibility IN ('public', 'authenticated', 'private', 'internal')
  ),
  CONSTRAINT storage_object_status_check CHECK (
    status IN ('pending', 'available', 'deletion_pending', 'deleted')
  ),
  CONSTRAINT storage_object_lifecycle_check CHECK (
    (status = 'pending' AND available_at IS NULL AND deleted_at IS NULL)
    OR (status = 'available' AND available_at IS NOT NULL AND deleted_at IS NULL)
    OR (status = 'deletion_pending' AND available_at IS NOT NULL AND deleted_at IS NULL)
    OR (status = 'deleted' AND deleted_at IS NOT NULL)
  )
);

CREATE INDEX storage_object_tenant_resource_idx
  ON ghm.storage_object (tenant_business_id, resource_type, resource_id, status, id);

CREATE INDEX storage_object_class_status_idx
  ON ghm.storage_object (object_class, status, created_at, id);

COMMIT;
