-- Establish the provider-neutral GHM Business Capability assertion relation.
-- Construction-only. No production migration or product cutover is authorized.
-- Canonical Capability taxonomy is ghm.capability and remains runtime read-only.

CREATE TABLE ghm.business_capability (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  business_id bigint NOT NULL
    REFERENCES ghm.business(id)
    ON DELETE CASCADE,

  capability_id uuid NOT NULL
    REFERENCES ghm.capability(id)
    ON DELETE RESTRICT,

  proficiency_level text,
  description text,

  assertion_status text NOT NULL DEFAULT 'active',
  assertion_basis text NOT NULL DEFAULT 'self_declared',
  verification_status text NOT NULL DEFAULT 'unverified',

  effective_from timestamptz NOT NULL DEFAULT now(),
  effective_until timestamptz,
  source_reference text,

  submitted_at timestamptz NOT NULL DEFAULT now(),
  verified_by bigint
    REFERENCES ghm.account_identity(id)
    ON DELETE SET NULL,
  verified_at timestamptz,
  verification_reason text,

  created_by bigint
    REFERENCES ghm.account_identity(id)
    ON DELETE SET NULL,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT business_capability_unique
    UNIQUE (business_id, capability_id),

  CONSTRAINT business_capability_proficiency_check
    CHECK (
      proficiency_level IS NULL
      OR proficiency_level IN (
        'foundational',
        'proficient',
        'advanced',
        'expert'
      )
    ),

  CONSTRAINT business_capability_description_check
    CHECK (
      description IS NULL
      OR char_length(btrim(description)) BETWEEN 1 AND 1000
    ),

  CONSTRAINT business_capability_assertion_status_check
    CHECK (assertion_status IN ('active', 'withdrawn')),

  CONSTRAINT business_capability_assertion_basis_check
    CHECK (
      assertion_basis IN (
        'self_declared',
        'documented',
        'observed',
        'third_party_attested'
      )
    ),

  CONSTRAINT business_capability_verification_status_check
    CHECK (
      verification_status IN (
        'unverified',
        'pending',
        'verified',
        'rejected',
        'revoked',
        'expired'
      )
    ),

  CONSTRAINT business_capability_effective_period_check
    CHECK (
      effective_until IS NULL
      OR effective_until > effective_from
    ),

  CONSTRAINT business_capability_source_reference_check
    CHECK (
      source_reference IS NULL
      OR char_length(btrim(source_reference)) BETWEEN 1 AND 500
    ),

  CONSTRAINT business_capability_verification_reason_check
    CHECK (
      verification_reason IS NULL
      OR char_length(btrim(verification_reason)) BETWEEN 1 AND 1000
    ),

  CONSTRAINT business_capability_verification_state_check
    CHECK (
      (
        verification_status IN ('unverified', 'pending')
        AND verified_by IS NULL
        AND verified_at IS NULL
        AND verification_reason IS NULL
      )
      OR
      (
        verification_status = 'verified'
        AND verified_by IS NOT NULL
        AND verified_at IS NOT NULL
        AND verification_reason IS NULL
      )
      OR
      (
        verification_status IN ('rejected', 'revoked')
        AND verified_by IS NOT NULL
        AND verified_at IS NOT NULL
        AND verification_reason IS NOT NULL
      )
      OR
      (
        verification_status = 'expired'
        AND verified_at IS NOT NULL
      )
    )
);

CREATE INDEX business_capability_business_state_idx
  ON ghm.business_capability (
    business_id,
    assertion_status,
    verification_status,
    effective_from DESC,
    id
  );

CREATE INDEX business_capability_capability_state_idx
  ON ghm.business_capability (
    capability_id,
    assertion_status,
    verification_status,
    business_id
  );

ALTER TABLE ghm.business_capability OWNER TO ghm_schema_owner;

GRANT USAGE ON SCHEMA ghm TO ghm_runtime;

GRANT SELECT
  ON TABLE ghm.business_capability
  TO ghm_runtime;

GRANT INSERT (
  business_id,
  capability_id,
  proficiency_level,
  description,
  effective_from,
  effective_until,
  source_reference,
  created_by
)
  ON TABLE ghm.business_capability
  TO ghm_runtime;

GRANT USAGE
  ON SEQUENCE ghm.business_capability_id_seq
  TO ghm_runtime;
