-- Opaque refresh credentials for an authentication_session family.
-- Stores HMAC token hashes only (pepper supplied by future runtime config — not in DB).
-- Construction-only. No Auth API / rotation runtime.

CREATE TABLE ghm.refresh_credential (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  session_id bigint NOT NULL
    REFERENCES ghm.authentication_session(id)
    ON DELETE CASCADE,

  token_hash bytea NOT NULL,

  issued_at timestamptz NOT NULL DEFAULT now(),
  used_at timestamptz,
  revoked_at timestamptz,

  predecessor_id bigint
    REFERENCES ghm.refresh_credential(id)
    ON DELETE SET NULL,

  CONSTRAINT refresh_credential_token_hash_unique
    UNIQUE (token_hash),

  CONSTRAINT refresh_credential_token_hash_nonempty_check
    CHECK (octet_length(token_hash) > 0),

  CONSTRAINT refresh_credential_used_after_issued_check
    CHECK (used_at IS NULL OR used_at >= issued_at),

  CONSTRAINT refresh_credential_revoked_after_issued_check
    CHECK (revoked_at IS NULL OR revoked_at >= issued_at)
);

-- At most one live tip per session family (supports atomic rotation concurrency).
CREATE UNIQUE INDEX refresh_credential_session_live_uidx
  ON ghm.refresh_credential (session_id)
  WHERE used_at IS NULL AND revoked_at IS NULL;

CREATE INDEX refresh_credential_session_issued_idx
  ON ghm.refresh_credential (session_id, issued_at DESC, id);

CREATE INDEX refresh_credential_predecessor_idx
  ON ghm.refresh_credential (predecessor_id)
  WHERE predecessor_id IS NOT NULL;

COMMENT ON TABLE ghm.refresh_credential IS
  'Opaque refresh credentials for a session family. token_hash is HMAC of the raw token; plaintext never stored. Partial unique live tip enforces single-successor rotation.';

ALTER TABLE ghm.refresh_credential OWNER TO ghm_schema_owner;

GRANT USAGE ON SCHEMA ghm TO ghm_runtime;

-- No runtime SELECT/DML until controlled Auth functions exist (token hashes must not be readable by ghm_runtime).
REVOKE ALL ON TABLE ghm.refresh_credential FROM ghm_runtime;

GRANT USAGE ON SEQUENCE ghm.refresh_credential_id_seq TO ghm_runtime;
