begin;

create table ghm.currency (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name text not null,
  symbol text not null,
  minor_unit integer not null default 2,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint currency_code_format
    check (code ~ '^[A-Z]{3}$'),

  constraint currency_name_not_blank
    check (btrim(name) <> ''),

  constraint currency_symbol_not_blank
    check (btrim(symbol) <> ''),

  constraint currency_minor_unit_range
    check (minor_unit between 0 and 6)
);

create table ghm.country (
  id bigint generated by default as identity primary key,
  code_alpha2 text not null unique,
  code_alpha3 text not null unique,
  name text not null,
  default_currency_id bigint
    references ghm.currency(id)
    on delete restrict,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),

  constraint country_alpha2_code_format
    check (code_alpha2 ~ '^[A-Z]{2}$'),

  constraint country_alpha3_code_format
    check (code_alpha3 ~ '^[A-Z]{3}$'),

  constraint country_name_not_blank
    check (btrim(name) <> '')
);

create index country_default_currency_id_idx
  on ghm.country(default_currency_id);

create trigger currency_set_updated_at
before update on ghm.currency
for each row
execute function ghm.set_updated_at();

create trigger country_set_updated_at
before update on ghm.country
for each row
execute function ghm.set_updated_at();

insert into ghm.currency (
  code,
  name,
  symbol,
  minor_unit
)
values (
  'ZAR',
  'South African Rand',
  'R',
  2
);

insert into ghm.country (
  code_alpha2,
  code_alpha3,
  name,
  default_currency_id
)
select
  'ZA',
  'ZAF',
  'South Africa',
  id
from ghm.currency
where code = 'ZAR';

grant select on table ghm.currency to ghm_runtime;
grant select on table ghm.country to ghm_runtime;

commit;
