-- Password recovery credentials (short-lived, single-use, HMAC hash only).
-- Construction-only. No email sending, no recovery runtime, no pepper/secret in DB.

CREATE TABLE ghm.password_recovery_credential (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  account_id bigint NOT NULL
    REFERENCES ghm.account_identity(id)
    ON DELETE CASCADE,

  token_hash bytea NOT NULL,

  created_at timestamptz NOT NULL DEFAULT now(),
  expires_at timestamptz NOT NULL,
  used_at timestamptz,
  revoked_at timestamptz,

  CONSTRAINT password_recovery_credential_token_hash_unique
    UNIQUE (token_hash),

  CONSTRAINT password_recovery_credential_token_hash_nonempty_check
    CHECK (octet_length(token_hash) > 0),

  CONSTRAINT password_recovery_credential_expires_after_created_check
    CHECK (expires_at > created_at),

  CONSTRAINT password_recovery_credential_used_after_created_check
    CHECK (used_at IS NULL OR used_at >= created_at),

  CONSTRAINT password_recovery_credential_revoked_after_created_check
    CHECK (revoked_at IS NULL OR revoked_at >= created_at)
);

CREATE INDEX password_recovery_credential_account_created_idx
  ON ghm.password_recovery_credential (account_id, created_at DESC, id);

COMMENT ON TABLE ghm.password_recovery_credential IS
  'Password recovery credentials. token_hash is HMAC of the raw token; plaintext never stored. TTL enforced via expires_at (runtime target 30 minutes). Successful redeem must revoke all auth sessions.';

ALTER TABLE ghm.password_recovery_credential OWNER TO ghm_schema_owner;

GRANT USAGE ON SCHEMA ghm TO ghm_runtime;

-- No runtime SELECT/DML until controlled Auth functions exist.
REVOKE ALL ON TABLE ghm.password_recovery_credential FROM ghm_runtime;

GRANT USAGE ON SEQUENCE ghm.password_recovery_credential_id_seq TO ghm_runtime;
