-- Authentication session (= refresh-token session family).
-- authentication_session.id is the stable session-family identity. No separate family table.
-- Construction-only. No Auth API / refresh runtime.

CREATE TABLE ghm.authentication_session (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  account_id bigint NOT NULL
    REFERENCES ghm.account_identity(id)
    ON DELETE CASCADE,

  session_status text NOT NULL DEFAULT 'active',
  created_at timestamptz NOT NULL DEFAULT now(),
  last_seen_at timestamptz NOT NULL DEFAULT now(),
  absolute_expires_at timestamptz NOT NULL,
  revoked_at timestamptz,
  revoke_reason text,

  CONSTRAINT authentication_session_status_check
    CHECK (session_status IN ('active', 'revoked')),

  CONSTRAINT authentication_session_absolute_after_created_check
    CHECK (absolute_expires_at > created_at),

  CONSTRAINT authentication_session_revoked_consistency_check
    CHECK (
      (session_status = 'active' AND revoked_at IS NULL)
      OR (session_status = 'revoked' AND revoked_at IS NOT NULL)
    )
);

CREATE INDEX authentication_session_account_status_idx
  ON ghm.authentication_session (account_id, session_status, id);

COMMENT ON TABLE ghm.authentication_session IS
  'One authenticated refresh-session family. id is the stable session-family identity. Inactivity = last_seen_at + 30 days; absolute = absolute_expires_at (90 days from create).';

ALTER TABLE ghm.authentication_session OWNER TO ghm_schema_owner;

GRANT USAGE ON SCHEMA ghm TO ghm_runtime;

GRANT SELECT
  ON TABLE ghm.authentication_session
  TO ghm_runtime;

REVOKE INSERT, UPDATE, DELETE
  ON TABLE ghm.authentication_session
  FROM ghm_runtime;

GRANT USAGE ON SEQUENCE ghm.authentication_session_id_seq TO ghm_runtime;
