-- Provider-neutral external business/org mapping into ghm.business.
-- Construction-only. Separate from person identity mapping. No product ID auto-equivalence.

CREATE TABLE ghm.business_external_mapping (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  provider text NOT NULL,
  external_business_id text NOT NULL,
  business_id bigint NOT NULL
    REFERENCES ghm.business(id)
    ON DELETE RESTRICT,

  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT business_external_mapping_provider_external_unique
    UNIQUE (provider, external_business_id),

  CONSTRAINT business_external_mapping_provider_nonblank_check
    CHECK (btrim(provider) <> ''),

  CONSTRAINT business_external_mapping_external_business_id_nonblank_check
    CHECK (btrim(external_business_id) <> '')
);

CREATE INDEX business_external_mapping_business_provider_idx
  ON ghm.business_external_mapping (business_id, provider);

COMMENT ON TABLE ghm.business_external_mapping IS
  'Maps (provider, external_business_id) to ghm.business.id. Product business/org IDs are not assumed equal to GHM business IDs.';

ALTER TABLE ghm.business_external_mapping OWNER TO ghm_schema_owner;

GRANT USAGE ON SCHEMA ghm TO ghm_runtime;

GRANT SELECT
  ON TABLE ghm.business_external_mapping
  TO ghm_runtime;

REVOKE INSERT, UPDATE, DELETE
  ON TABLE ghm.business_external_mapping
  FROM ghm_runtime;

GRANT USAGE ON SEQUENCE ghm.business_external_mapping_id_seq TO ghm_runtime;
