-- Provider-neutral external person identity mapping into ghm.account_identity.
-- Construction-only. No Supabase auto-import, no Auth API, no product cutover.

CREATE TABLE ghm.account_external_identity (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  provider text NOT NULL,
  subject text NOT NULL,
  account_id bigint NOT NULL
    REFERENCES ghm.account_identity(id)
    ON DELETE CASCADE,

  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT account_external_identity_provider_subject_unique
    UNIQUE (provider, subject),

  CONSTRAINT account_external_identity_provider_nonblank_check
    CHECK (btrim(provider) <> ''),

  CONSTRAINT account_external_identity_subject_nonblank_check
    CHECK (btrim(subject) <> '')
);

CREATE INDEX account_external_identity_account_provider_idx
  ON ghm.account_external_identity (account_id, provider);

COMMENT ON TABLE ghm.account_external_identity IS
  'Maps (provider, subject) to canonical ghm.account_identity.id. Supabase UUID subjects are not inherently GHM identities.';

ALTER TABLE ghm.account_external_identity OWNER TO ghm_schema_owner;

GRANT USAGE ON SCHEMA ghm TO ghm_runtime;

GRANT SELECT
  ON TABLE ghm.account_external_identity
  TO ghm_runtime;

REVOKE INSERT, UPDATE, DELETE
  ON TABLE ghm.account_external_identity
  FROM ghm_runtime;

GRANT USAGE ON SEQUENCE ghm.account_external_identity_id_seq TO ghm_runtime;
