CREATE TABLE ghm.notification (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES ghm.account_identity(id) ON DELETE CASCADE,
  type text NOT NULL,
  title text NOT NULL,
  body text NOT NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  is_read boolean NOT NULL DEFAULT false,
  read_at timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT notification_type_check
    CHECK (type IN ('system', 'lead', 'verification', 'project', 'quote', 'message')),
  CONSTRAINT notification_title_length_check
    CHECK (char_length(btrim(title)) BETWEEN 1 AND 160),
  CONSTRAINT notification_body_length_check
    CHECK (char_length(btrim(body)) BETWEEN 1 AND 2000),
  CONSTRAINT notification_metadata_object_check
    CHECK (jsonb_typeof(metadata) = 'object'),
  CONSTRAINT notification_read_state_check
    CHECK ((is_read = false AND read_at IS NULL) OR (is_read = true AND read_at IS NOT NULL))
);

CREATE INDEX notification_user_created_at_idx
  ON ghm.notification (user_id, created_at DESC, id DESC);

CREATE INDEX notification_user_unread_created_at_idx
  ON ghm.notification (user_id, created_at DESC, id DESC)
  WHERE is_read = false;

CREATE INDEX notification_type_created_at_idx
  ON ghm.notification (type, created_at DESC, id DESC);

ALTER TABLE ghm.notification OWNER TO ghm_schema_owner;

GRANT SELECT ON TABLE ghm.notification TO ghm_runtime;

GRANT INSERT (
  user_id,
  type,
  title,
  body,
  metadata
)
ON TABLE ghm.notification TO ghm_runtime;

GRANT UPDATE (is_read, read_at)
  ON TABLE ghm.notification
  TO ghm_runtime;

GRANT USAGE
  ON SEQUENCE ghm.notification_id_seq
  TO ghm_runtime;
