-- Contact Access Slice D: dedicated verified commercial authorization facts
-- for Model A (Business + Opportunity). Provider-neutral; not payment rows,
-- not ghm.commercial_event. Does not execute provider verification.

CREATE TABLE ghm.contact_access_commercial_fact (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  business_id bigint NOT NULL
    REFERENCES ghm.business(id)
    ON DELETE RESTRICT,

  opportunity_id bigint NOT NULL
    REFERENCES ghm.opportunity(id)
    ON DELETE RESTRICT,

  idempotency_key text NOT NULL,

  verification_status text NOT NULL DEFAULT 'verified',

  commercial_source text NOT NULL,

  verified_by_account_id bigint
    REFERENCES ghm.account_identity(id)
    ON DELETE SET NULL,

  verified_at timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT contact_access_commercial_fact_idempotency_key_valid
    CHECK (length(btrim(idempotency_key)) BETWEEN 8 AND 200),

  CONSTRAINT contact_access_commercial_fact_verification_status_valid
    CHECK (verification_status = 'verified'),

  CONSTRAINT contact_access_commercial_fact_commercial_source_valid
    CHECK (length(btrim(commercial_source)) BETWEEN 1 AND 100)
);

CREATE UNIQUE INDEX contact_access_commercial_fact_idempotency_uq
  ON ghm.contact_access_commercial_fact (idempotency_key);

CREATE INDEX contact_access_commercial_fact_business_opportunity_idx
  ON ghm.contact_access_commercial_fact (business_id, opportunity_id, verified_at DESC, id);

ALTER TABLE ghm.contact_access_entitlement
  ADD COLUMN contact_access_commercial_fact_id bigint
    REFERENCES ghm.contact_access_commercial_fact(id)
    ON DELETE RESTRICT;

ALTER TABLE ghm.contact_access_entitlement
  DROP CONSTRAINT contact_access_grant_reason_valid;

ALTER TABLE ghm.contact_access_entitlement
  ADD CONSTRAINT contact_access_grant_reason_valid
    CHECK (grant_reason IN ('manual_promotional', 'verified_commercial'));

ALTER TABLE ghm.contact_access_entitlement
  ADD CONSTRAINT contact_access_commercial_fact_grant_consistency
    CHECK (
      (
        grant_reason = 'manual_promotional'
        AND contact_access_commercial_fact_id IS NULL
      )
      OR (
        grant_reason = 'verified_commercial'
        AND contact_access_commercial_fact_id IS NOT NULL
        AND commercial_event_reference IS NOT NULL
        AND length(btrim(commercial_event_reference)) BETWEEN 1 AND 200
      )
    );

ALTER TABLE ghm.contact_access_commercial_fact OWNER TO ghm_schema_owner;

REVOKE INSERT, UPDATE, DELETE
  ON TABLE ghm.contact_access_commercial_fact
  FROM ghm_runtime;

GRANT SELECT
  ON TABLE ghm.contact_access_commercial_fact
  TO ghm_runtime;

GRANT SELECT, INSERT, UPDATE, DELETE
  ON TABLE ghm.contact_access_commercial_fact
  TO ghm_migrator;

GRANT USAGE, SELECT ON SEQUENCE
  ghm.contact_access_commercial_fact_id_seq
  TO ghm_migrator;

CREATE OR REPLACE FUNCTION ghm.assert_contact_access_grant_eligibility(
  p_business_id bigint,
  p_opportunity_id bigint,
  p_actor_account_id bigint
)
RETURNS void
LANGUAGE plpgsql
SET search_path = pg_catalog, ghm
AS $$
DECLARE
  opportunity_lifecycle text;
  enquiry_count integer;
  enquiry_business_id bigint;
BEGIN
  IF p_actor_account_id IS NULL OR p_actor_account_id <= 0 THEN
    RAISE EXCEPTION 'Contact Access actor context required';
  END IF;

  IF p_business_id IS NULL OR p_business_id <= 0 THEN
    RAISE EXCEPTION 'businessId must be a positive integer';
  END IF;

  IF p_opportunity_id IS NULL OR p_opportunity_id <= 0 THEN
    RAISE EXCEPTION 'opportunityId must be a positive integer';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM ghm.business b
     WHERE b.id = p_business_id
       AND b.is_active = true
  ) THEN
    RAISE EXCEPTION 'Business is not eligible for Contact Access';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM ghm.business_membership bm
     WHERE bm.business_id = p_business_id
       AND bm.account_id = p_actor_account_id
       AND bm.membership_status = 'active'
       AND bm.membership_role IN ('owner', 'administrator')
  ) THEN
    RAISE EXCEPTION 'Business management permission required';
  END IF;

  SELECT o.lifecycle_status INTO opportunity_lifecycle
    FROM ghm.opportunity o
   WHERE o.id = p_opportunity_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Opportunity not found';
  END IF;

  IF opportunity_lifecycle NOT IN ('open', 'responding', 'evaluating') THEN
    RAISE EXCEPTION 'Opportunity is not eligible for Contact Access grant';
  END IF;

  SELECT COUNT(*), MIN(e.business_id)
    INTO enquiry_count, enquiry_business_id
    FROM ghm.enquiry e
   WHERE e.opportunity_id = p_opportunity_id;

  IF enquiry_count = 0 THEN
    RAISE EXCEPTION 'Opportunity is not Enquiry-backed';
  END IF;

  IF enquiry_count > 1 THEN
    RAISE EXCEPTION 'Opportunity Enquiry association is ambiguous';
  END IF;

  IF enquiry_business_id IS DISTINCT FROM p_business_id THEN
    RAISE EXCEPTION 'Contact Access Business does not match Enquiry recipient';
  END IF;
END;
$$;

ALTER FUNCTION ghm.assert_contact_access_grant_eligibility(bigint, bigint, bigint)
  OWNER TO ghm_schema_owner;
REVOKE ALL ON FUNCTION ghm.assert_contact_access_grant_eligibility(bigint, bigint, bigint) FROM PUBLIC;

CREATE OR REPLACE FUNCTION ghm.grant_contact_access_commercial(
  p_business_id bigint,
  p_opportunity_id bigint,
  p_idempotency_key text,
  p_commercial_source text
)
RETURNS TABLE (
  commercial_fact_id bigint,
  entitlement_id bigint,
  business_id bigint,
  opportunity_id bigint,
  authorization_status text,
  grant_reason text,
  grant_source text,
  granted_by_account_id bigint,
  granted_at timestamptz,
  commercial_event_reference text,
  revoked_at timestamptz,
  revoked_by_account_id bigint,
  revocation_reason text,
  created_at timestamptz,
  updated_at timestamptz
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, ghm
AS $$
DECLARE
  actor_account_id bigint;
  normalized_key text;
  normalized_source text;
  fact_row ghm.contact_access_commercial_fact%ROWTYPE;
  existing ghm.contact_access_entitlement%ROWTYPE;
  inserted ghm.contact_access_entitlement%ROWTYPE;
  fact_reference text;
BEGIN
  BEGIN
    actor_account_id := nullif(btrim(current_setting('ghm.actor_account_id', true)), '')::bigint;
  EXCEPTION
    WHEN invalid_text_representation THEN
      RAISE EXCEPTION 'Contact Access actor context required';
  END;

  normalized_key := btrim(p_idempotency_key);
  IF normalized_key IS NULL OR length(normalized_key) < 8 OR length(normalized_key) > 200 THEN
    RAISE EXCEPTION 'idempotencyKey must be between 8 and 200 characters';
  END IF;

  normalized_source := btrim(p_commercial_source);
  IF normalized_source IS NULL OR length(normalized_source) < 1 OR length(normalized_source) > 100 THEN
    RAISE EXCEPTION 'commercialSource must be between 1 and 100 characters';
  END IF;

  PERFORM ghm.assert_contact_access_grant_eligibility(
    p_business_id,
    p_opportunity_id,
    actor_account_id
  );

  BEGIN
    INSERT INTO ghm.contact_access_commercial_fact (
      business_id,
      opportunity_id,
      idempotency_key,
      verification_status,
      commercial_source,
      verified_by_account_id,
      verified_at
    ) VALUES (
      p_business_id,
      p_opportunity_id,
      normalized_key,
      'verified',
      normalized_source,
      actor_account_id,
      now()
    )
    RETURNING * INTO fact_row;
  EXCEPTION
    WHEN unique_violation THEN
      SELECT * INTO fact_row
        FROM ghm.contact_access_commercial_fact cacf
       WHERE cacf.idempotency_key = normalized_key;

      IF NOT FOUND THEN
        RAISE;
      END IF;

      IF fact_row.business_id <> p_business_id
         OR fact_row.opportunity_id <> p_opportunity_id THEN
        RAISE EXCEPTION 'Commercial fact idempotency scope mismatch';
      END IF;
  END;

  fact_reference := 'contact_access_commercial_fact:' || fact_row.id::text;

  PERFORM pg_advisory_xact_lock(
    hashtext('ghm.contact_access.grant.business:' || p_business_id::text),
    hashtext('ghm.contact_access.grant.opportunity:' || p_opportunity_id::text)
  );

  SELECT * INTO existing
    FROM ghm.contact_access_entitlement cae
   WHERE cae.business_id = p_business_id
     AND cae.opportunity_id = p_opportunity_id
     AND cae.authorization_status = 'active'
   FOR UPDATE;

  IF FOUND THEN
    IF existing.grant_reason = 'verified_commercial'
       AND existing.contact_access_commercial_fact_id = fact_row.id THEN
      RETURN QUERY
      SELECT
        fact_row.id,
        existing.id,
        existing.business_id,
        existing.opportunity_id,
        existing.authorization_status,
        existing.grant_reason,
        existing.grant_source,
        existing.granted_by_account_id,
        existing.granted_at,
        existing.commercial_event_reference,
        existing.revoked_at,
        existing.revoked_by_account_id,
        existing.revocation_reason,
        existing.created_at,
        existing.updated_at;
      RETURN;
    END IF;

    RETURN QUERY
    SELECT
      fact_row.id,
      existing.id,
      existing.business_id,
      existing.opportunity_id,
      existing.authorization_status,
      existing.grant_reason,
      existing.grant_source,
      existing.granted_by_account_id,
      existing.granted_at,
      existing.commercial_event_reference,
      existing.revoked_at,
      existing.revoked_by_account_id,
      existing.revocation_reason,
      existing.created_at,
      existing.updated_at;
    RETURN;
  END IF;

  BEGIN
    INSERT INTO ghm.contact_access_entitlement (
      business_id,
      opportunity_id,
      authorization_status,
      grant_reason,
      grant_source,
      granted_by_account_id,
      granted_at,
      commercial_event_reference,
      contact_access_commercial_fact_id
    ) VALUES (
      p_business_id,
      p_opportunity_id,
      'active',
      'verified_commercial',
      normalized_source,
      actor_account_id,
      now(),
      fact_reference,
      fact_row.id
    )
    RETURNING * INTO inserted;
  EXCEPTION
    WHEN unique_violation THEN
      SELECT * INTO existing
        FROM ghm.contact_access_entitlement cae
       WHERE cae.business_id = p_business_id
         AND cae.opportunity_id = p_opportunity_id
         AND cae.authorization_status = 'active'
       FOR UPDATE;

      IF NOT FOUND THEN
        RAISE;
      END IF;

      RETURN QUERY
      SELECT
        fact_row.id,
        existing.id,
        existing.business_id,
        existing.opportunity_id,
        existing.authorization_status,
        existing.grant_reason,
        existing.grant_source,
        existing.granted_by_account_id,
        existing.granted_at,
        existing.commercial_event_reference,
        existing.revoked_at,
        existing.revoked_by_account_id,
        existing.revocation_reason,
        existing.created_at,
        existing.updated_at;
      RETURN;
  END;

  INSERT INTO ghm.contact_access_event (
    entitlement_id,
    business_id,
    opportunity_id,
    event_type,
    actor_account_id,
    source,
    reason,
    payload
  ) VALUES (
    inserted.id,
    inserted.business_id,
    inserted.opportunity_id,
    'granted',
    actor_account_id,
    normalized_source,
    'verified_commercial',
    jsonb_build_object(
      'grant_reason', 'verified_commercial',
      'contact_access_commercial_fact_id', fact_row.id
    )
  );

  RETURN QUERY
  SELECT
    fact_row.id,
    inserted.id,
    inserted.business_id,
    inserted.opportunity_id,
    inserted.authorization_status,
    inserted.grant_reason,
    inserted.grant_source,
    inserted.granted_by_account_id,
    inserted.granted_at,
    inserted.commercial_event_reference,
    inserted.revoked_at,
    inserted.revoked_by_account_id,
    inserted.revocation_reason,
    inserted.created_at,
    inserted.updated_at;
END;
$$;

ALTER FUNCTION ghm.grant_contact_access_commercial(bigint, bigint, text, text)
  OWNER TO ghm_schema_owner;
REVOKE ALL ON FUNCTION ghm.grant_contact_access_commercial(bigint, bigint, text, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION ghm.grant_contact_access_commercial(bigint, bigint, text, text) TO ghm_runtime;
