CREATE TABLE ghm.enquiry (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  business_id bigint NOT NULL REFERENCES ghm.business(id),
  customer_id bigint NOT NULL REFERENCES ghm.account_identity(id),
  customer_name text NOT NULL,
  customer_phone text,
  customer_email text,
  project text NOT NULL,
  description text NOT NULL,
  city text,
  budget_min numeric(12,2),
  budget_max numeric(12,2),
  urgency text NOT NULL DEFAULT 'standard',
  source text NOT NULL DEFAULT 'marketplace',
  status text NOT NULL DEFAULT 'new',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT enquiry_customer_name_length_check
    CHECK (char_length(btrim(customer_name)) BETWEEN 1 AND 200),
  CONSTRAINT enquiry_customer_phone_length_check
    CHECK (customer_phone IS NULL OR char_length(btrim(customer_phone)) BETWEEN 7 AND 32),
  CONSTRAINT enquiry_customer_email_length_check
    CHECK (customer_email IS NULL OR char_length(btrim(customer_email)) BETWEEN 3 AND 320),
  CONSTRAINT enquiry_project_length_check
    CHECK (char_length(btrim(project)) BETWEEN 1 AND 200),
  CONSTRAINT enquiry_description_length_check
    CHECK (char_length(btrim(description)) BETWEEN 10 AND 5000),
  CONSTRAINT enquiry_city_length_check
    CHECK (city IS NULL OR char_length(btrim(city)) BETWEEN 1 AND 120),
  CONSTRAINT enquiry_budget_min_check
    CHECK (budget_min IS NULL OR budget_min >= 0),
  CONSTRAINT enquiry_budget_max_check
    CHECK (budget_max IS NULL OR budget_max >= 0),
  CONSTRAINT enquiry_budget_range_check
    CHECK (budget_min IS NULL OR budget_max IS NULL OR budget_max >= budget_min),
  CONSTRAINT enquiry_urgency_check
    CHECK (urgency IN ('standard', 'urgent', 'emergency')),
  CONSTRAINT enquiry_source_check
    CHECK (source IN ('marketplace', 'directory', 'ai_quote', 'direct')),
  CONSTRAINT enquiry_status_check
    CHECK (status IN ('new', 'contacted', 'qualified', 'quoted', 'won', 'lost', 'archived'))
);

CREATE INDEX enquiry_customer_created_idx
  ON ghm.enquiry (customer_id, created_at DESC, id);

CREATE INDEX enquiry_business_created_idx
  ON ghm.enquiry (business_id, created_at DESC, id);

CREATE INDEX enquiry_business_status_created_idx
  ON ghm.enquiry (business_id, status, created_at DESC, id);

ALTER TABLE ghm.enquiry OWNER TO ghm_schema_owner;

GRANT SELECT ON TABLE ghm.enquiry TO ghm_runtime;

GRANT INSERT (
  business_id,
  customer_id,
  customer_name,
  customer_phone,
  customer_email,
  project,
  description,
  city,
  budget_min,
  budget_max,
  urgency,
  source
)
ON TABLE ghm.enquiry TO ghm_runtime;

GRANT UPDATE (status)
  ON TABLE ghm.enquiry
  TO ghm_runtime;

GRANT USAGE
  ON SEQUENCE ghm.enquiry_id_seq
  TO ghm_runtime;
