-- Establish the provider-neutral reference identifiers required by Commercial pricing.
-- This migration is construction-only. It does not copy Supabase regional configuration.

CREATE TABLE ghm.currency (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code text NOT NULL UNIQUE,
  name text NOT NULL,
  symbol text NOT NULL,
  minor_unit_digits integer NOT NULL DEFAULT 2,
  lifecycle_status text NOT NULL DEFAULT 'active',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT currency_code_format CHECK (code ~ '^[A-Z]{3}$'),
  CONSTRAINT currency_name_not_blank CHECK (btrim(name) <> ''),
  CONSTRAINT currency_symbol_not_blank CHECK (btrim(symbol) <> ''),
  CONSTRAINT currency_minor_unit_digits_valid CHECK (minor_unit_digits BETWEEN 0 AND 6),
  CONSTRAINT currency_lifecycle_valid CHECK (lifecycle_status IN ('active', 'retired'))
);

CREATE TABLE ghm.country (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  alpha_2_code text NOT NULL UNIQUE,
  alpha_3_code text NOT NULL UNIQUE,
  name text NOT NULL,
  default_currency_id bigint REFERENCES ghm.currency(id) ON DELETE RESTRICT,
  lifecycle_status text NOT NULL DEFAULT 'active',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT country_alpha_2_format CHECK (alpha_2_code ~ '^[A-Z]{2}$'),
  CONSTRAINT country_alpha_3_format CHECK (alpha_3_code ~ '^[A-Z]{3}$'),
  CONSTRAINT country_name_not_blank CHECK (btrim(name) <> ''),
  CONSTRAINT country_lifecycle_valid CHECK (lifecycle_status IN ('active', 'retired'))
);

CREATE INDEX country_default_currency_id_idx ON ghm.country(default_currency_id);

INSERT INTO ghm.currency (code, name, symbol, minor_unit_digits)
VALUES ('ZAR', 'South African Rand', 'R', 2)
ON CONFLICT (code) DO NOTHING;

INSERT INTO ghm.country (alpha_2_code, alpha_3_code, name, default_currency_id)
SELECT 'ZA', 'ZAF', 'South Africa', currency.id
FROM ghm.currency AS currency
WHERE currency.code = 'ZAR'
ON CONFLICT (alpha_2_code) DO NOTHING;

ALTER TABLE ghm.currency OWNER TO ghm_schema_owner;
ALTER TABLE ghm.country OWNER TO ghm_schema_owner;

GRANT SELECT ON TABLE ghm.currency, ghm.country TO ghm_runtime;
GRANT USAGE, SELECT ON SEQUENCE ghm.currency_id_seq, ghm.country_id_seq TO ghm_runtime;

ALTER DEFAULT PRIVILEGES FOR ROLE ghm_schema_owner IN SCHEMA ghm
  GRANT USAGE, SELECT ON SEQUENCES TO ghm_runtime;
