-- Establish the first governed GHM Project relation.
-- Construction-only migration; production cutover is not part of this change.
-- The relation is account-owned and deliberately independent of Business membership.

CREATE TABLE ghm.project (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  account_id bigint NOT NULL
    REFERENCES ghm.account_identity(id)
    ON DELETE CASCADE,
  title text NOT NULL,
  description text NOT NULL,
  category text NOT NULL,
  province text NOT NULL,
  city text NOT NULL,
  budget_min numeric(12,2),
  budget_max numeric(12,2),
  urgency text NOT NULL DEFAULT 'standard',
  status text NOT NULL DEFAULT 'open',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT project_title_length_ck
    CHECK (char_length(btrim(title)) BETWEEN 5 AND 160),
  CONSTRAINT project_description_length_ck
    CHECK (char_length(btrim(description)) BETWEEN 20 AND 5000),
  CONSTRAINT project_category_length_ck
    CHECK (char_length(btrim(category)) BETWEEN 2 AND 80),
  CONSTRAINT project_province_length_ck
    CHECK (char_length(btrim(province)) BETWEEN 2 AND 80),
  CONSTRAINT project_city_length_ck
    CHECK (char_length(btrim(city)) BETWEEN 2 AND 120),
  CONSTRAINT project_budget_min_nonnegative_ck
    CHECK (budget_min IS NULL OR budget_min >= 0),
  CONSTRAINT project_budget_max_nonnegative_ck
    CHECK (budget_max IS NULL OR budget_max >= 0),
  CONSTRAINT project_budget_range_ck
    CHECK (
      budget_min IS NULL
      OR budget_max IS NULL
      OR budget_max >= budget_min
    ),
  CONSTRAINT project_urgency_ck
    CHECK (urgency IN ('standard', 'urgent', 'emergency')),
  CONSTRAINT project_status_ck
    CHECK (status IN ('open', 'in_progress', 'completed', 'cancelled'))
);

-- Owner history/listing access.
CREATE INDEX project_account_created_idx
  ON ghm.project (account_id, created_at DESC);

-- Open-project retrieval is a governed first-slice access pattern. This is
-- intentionally narrower than the Connect marketplace projection indexes.
CREATE INDEX project_open_created_idx
  ON ghm.project (created_at DESC)
  WHERE status = 'open';

GRANT USAGE ON SCHEMA ghm TO ghm_runtime;

GRANT SELECT
  ON TABLE ghm.project
  TO ghm_runtime;

-- INSERT omits database-generated id/status/timestamps. Status therefore uses
-- its database default of 'open' and cannot be supplied by the runtime role.
GRANT INSERT (
  account_id,
  title,
  description,
  category,
  province,
  city,
  budget_min,
  budget_max,
  urgency
)
  ON TABLE ghm.project
  TO ghm_runtime;

-- Runtime updates are restricted to the mutable Project fields. account_id
-- and status are intentionally absent from this privilege grant.
GRANT UPDATE (
  title,
  description,
  category,
  province,
  city,
  budget_min,
  budget_max,
  urgency,
  updated_at
)
  ON TABLE ghm.project
  TO ghm_runtime;

GRANT USAGE
  ON SEQUENCE ghm.project_id_seq
  TO ghm_runtime;

ALTER DEFAULT PRIVILEGES FOR ROLE ghm_schema_owner IN SCHEMA ghm
  GRANT USAGE ON SEQUENCES TO ghm_runtime;

-- No DELETE privilege is granted to ghm_runtime.
-- No blanket table DML or arbitrary sequence privilege is granted.
-- Owner predicates, open-status update rules, and authenticated context
-- binding remain explicit repository/service responsibilities.
