CREATE TABLE ghm.project_quote (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  project_id bigint NOT NULL
    REFERENCES ghm.project(id)
    ON DELETE RESTRICT,
  business_id bigint NOT NULL
    REFERENCES ghm.business(id)
    ON DELETE RESTRICT,

  amount numeric(12,2) NOT NULL,
  labour_min numeric(12,2),
  labour_max numeric(12,2),
  materials_min numeric(12,2),
  materials_max numeric(12,2),
  total_min numeric(12,2),
  total_max numeric(12,2),
  duration_days integer,
  description text,

  status text NOT NULL DEFAULT 'submitted',

  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT project_quote_project_business_unique
    UNIQUE (project_id, business_id),

  CONSTRAINT project_quote_amount_nonnegative_ck
    CHECK (amount >= 0),

  CONSTRAINT project_quote_labour_min_nonnegative_ck
    CHECK (labour_min IS NULL OR labour_min >= 0),

  CONSTRAINT project_quote_labour_max_nonnegative_ck
    CHECK (labour_max IS NULL OR labour_max >= 0),

  CONSTRAINT project_quote_labour_range_ck
    CHECK (
      labour_min IS NULL
      OR labour_max IS NULL
      OR labour_max >= labour_min
    ),

  CONSTRAINT project_quote_materials_min_nonnegative_ck
    CHECK (materials_min IS NULL OR materials_min >= 0),

  CONSTRAINT project_quote_materials_max_nonnegative_ck
    CHECK (materials_max IS NULL OR materials_max >= 0),

  CONSTRAINT project_quote_materials_range_ck
    CHECK (
      materials_min IS NULL
      OR materials_max IS NULL
      OR materials_max >= materials_min
    ),

  CONSTRAINT project_quote_total_min_nonnegative_ck
    CHECK (total_min IS NULL OR total_min >= 0),

  CONSTRAINT project_quote_total_max_nonnegative_ck
    CHECK (total_max IS NULL OR total_max >= 0),

  CONSTRAINT project_quote_total_range_ck
    CHECK (
      total_min IS NULL
      OR total_max IS NULL
      OR total_max >= total_min
    ),

  CONSTRAINT project_quote_duration_days_ck
    CHECK (
      duration_days IS NULL
      OR duration_days BETWEEN 1 AND 3650
    ),

  CONSTRAINT project_quote_description_length_ck
    CHECK (
      description IS NULL
      OR char_length(btrim(description)) BETWEEN 10 AND 5000
    ),

  CONSTRAINT project_quote_status_ck
    CHECK (
      status IN (
        'submitted',
        'accepted',
        'rejected',
        'withdrawn'
      )
    )
);

CREATE INDEX project_quote_project_created_idx
  ON ghm.project_quote (project_id, created_at DESC);

CREATE INDEX project_quote_business_created_idx
  ON ghm.project_quote (business_id, created_at DESC);

CREATE INDEX project_quote_project_status_idx
  ON ghm.project_quote (project_id, status);

CREATE UNIQUE INDEX project_quote_one_accepted_per_project_idx
  ON ghm.project_quote (project_id)
  WHERE status = 'accepted';

GRANT USAGE ON SCHEMA ghm TO ghm_runtime;

GRANT SELECT ON TABLE ghm.project_quote TO ghm_runtime;

GRANT INSERT (
  project_id,
  business_id,
  amount,
  labour_min,
  labour_max,
  materials_min,
  materials_max,
  total_min,
  total_max,
  duration_days,
  description
) ON TABLE ghm.project_quote TO ghm_runtime;

GRANT UPDATE (
  amount,
  labour_min,
  labour_max,
  materials_min,
  materials_max,
  total_min,
  total_max,
  duration_days,
  description,
  updated_at,
  status
) ON TABLE ghm.project_quote TO ghm_runtime;

GRANT USAGE ON SEQUENCE ghm.project_quote_id_seq TO ghm_runtime;

ALTER DEFAULT PRIVILEGES FOR ROLE ghm_schema_owner IN SCHEMA ghm
  GRANT USAGE ON SEQUENCES TO ghm_runtime;

-- No DELETE privilege.
-- Column-level UPDATE(status) is reserved for governed accept/reject decisions.
-- No blanket ALL/table-wide DML privileges.




