-- Construct the provider-neutral GHM Campaign root for KBM AI Marketing.
-- Construction-only. No production migration, HTTP, child resources, storage, AI, or cutover is authorized.

CREATE TABLE ghm.campaign (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  business_id bigint NOT NULL
    REFERENCES ghm.business(id)
    ON DELETE RESTRICT,

  created_by_account_id bigint NOT NULL
    REFERENCES ghm.account_identity(id)
    ON DELETE RESTRICT,

  title text NOT NULL,
  status text NOT NULL DEFAULT 'draft',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT campaign_title_valid
    CHECK (length(btrim(title)) BETWEEN 1 AND 200),
  CONSTRAINT campaign_status_valid
    CHECK (status IN ('draft', 'active', 'archived'))
);

CREATE INDEX campaign_business_created_idx
  ON ghm.campaign (business_id, created_at DESC, id);

CREATE INDEX campaign_business_status_created_idx
  ON ghm.campaign (business_id, status, created_at DESC, id);

CREATE INDEX campaign_creator_created_idx
  ON ghm.campaign (created_by_account_id, created_at DESC, id);

ALTER TABLE ghm.campaign OWNER TO ghm_schema_owner;

GRANT USAGE ON SCHEMA ghm TO ghm_runtime;

GRANT SELECT
  ON TABLE ghm.campaign
  TO ghm_runtime;

REVOKE INSERT, UPDATE, DELETE
  ON TABLE ghm.campaign
  FROM ghm_runtime;

GRANT USAGE ON SEQUENCE ghm.campaign_id_seq TO ghm_runtime;

CREATE OR REPLACE FUNCTION ghm.create_campaign(
  p_account_id bigint,
  p_business_id bigint,
  p_title text
)
RETURNS TABLE (
  id bigint,
  business_id bigint,
  created_by_account_id bigint,
  title text,
  status text,
  created_at timestamptz,
  updated_at timestamptz
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, ghm
AS $$
DECLARE
  normalized_title text;
BEGIN
  IF p_account_id IS NULL OR p_account_id <= 0 THEN
    RAISE EXCEPTION 'Account ID must be a positive integer';
  END IF;

  IF p_business_id IS NULL OR p_business_id <= 0 THEN
    RAISE EXCEPTION 'Business ID must be a positive integer';
  END IF;

  normalized_title := btrim(p_title);
  IF normalized_title IS NULL OR length(normalized_title) < 1 OR length(normalized_title) > 200 THEN
    RAISE EXCEPTION 'Campaign title must be between 1 and 200 characters';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM ghm.business
     WHERE ghm.business.id = p_business_id
       AND ghm.business.is_active = true
  ) THEN
    RAISE EXCEPTION 'Business is not eligible for campaign creation';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM ghm.business_membership
     WHERE business_id = p_business_id
       AND account_id = p_account_id
       AND membership_status = 'active'
       AND membership_role IN ('owner', 'administrator')
  ) THEN
    RAISE EXCEPTION 'Business management permission required';
  END IF;

  RETURN QUERY
  INSERT INTO ghm.campaign (business_id, created_by_account_id, title, status)
  VALUES (p_business_id, p_account_id, normalized_title, 'draft')
  RETURNING
    ghm.campaign.id,
    ghm.campaign.business_id,
    ghm.campaign.created_by_account_id,
    ghm.campaign.title,
    ghm.campaign.status,
    ghm.campaign.created_at,
    ghm.campaign.updated_at;
END;
$$;

ALTER FUNCTION ghm.create_campaign(bigint, bigint, text)
  OWNER TO ghm_schema_owner;
REVOKE ALL ON FUNCTION ghm.create_campaign(bigint, bigint, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION ghm.create_campaign(bigint, bigint, text) TO ghm_runtime;

CREATE OR REPLACE FUNCTION ghm.update_campaign(
  p_account_id bigint,
  p_campaign_id bigint,
  p_title text,
  p_status text
)
RETURNS TABLE (
  id bigint,
  business_id bigint,
  created_by_account_id bigint,
  title text,
  status text,
  created_at timestamptz,
  updated_at timestamptz
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, ghm
AS $$
DECLARE
  current_row ghm.campaign%ROWTYPE;
  next_title text;
  next_status text;
  normalized_title text;
BEGIN
  IF p_account_id IS NULL OR p_account_id <= 0 THEN
    RAISE EXCEPTION 'Account ID must be a positive integer';
  END IF;

  IF p_campaign_id IS NULL OR p_campaign_id <= 0 THEN
    RAISE EXCEPTION 'Campaign ID must be a positive integer';
  END IF;

  IF p_title IS NULL AND p_status IS NULL THEN
    RAISE EXCEPTION 'Campaign update requires at least one field';
  END IF;

  SELECT * INTO current_row
    FROM ghm.campaign
   WHERE ghm.campaign.id = p_campaign_id
   FOR UPDATE;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Campaign not found or management permission required';
  END IF;

  IF NOT EXISTS (
    SELECT 1 FROM ghm.business_membership
     WHERE business_id = current_row.business_id
       AND account_id = p_account_id
       AND membership_status = 'active'
       AND membership_role IN ('owner', 'administrator')
  ) THEN
    RAISE EXCEPTION 'Campaign not found or management permission required';
  END IF;

  next_title := current_row.title;
  next_status := current_row.status;

  IF p_title IS NOT NULL THEN
    IF current_row.status = 'archived' THEN
      RAISE EXCEPTION 'Archived campaign title cannot be updated';
    END IF;
    IF current_row.status NOT IN ('draft', 'active') THEN
      RAISE EXCEPTION 'Campaign title cannot be updated in the current status';
    END IF;
    normalized_title := btrim(p_title);
    IF normalized_title IS NULL OR length(normalized_title) < 1 OR length(normalized_title) > 200 THEN
      RAISE EXCEPTION 'Campaign title must be between 1 and 200 characters';
    END IF;
    next_title := normalized_title;
  END IF;

  IF p_status IS NOT NULL THEN
    IF p_status NOT IN ('draft', 'active', 'archived') THEN
      RAISE EXCEPTION 'Invalid campaign status';
    END IF;
    IF current_row.status = p_status THEN
      next_status := current_row.status;
    ELSIF current_row.status = 'draft' AND p_status IN ('active', 'archived') THEN
      next_status := p_status;
    ELSIF current_row.status = 'active' AND p_status = 'archived' THEN
      next_status := p_status;
    ELSE
      RAISE EXCEPTION 'Invalid campaign status transition: % -> %', current_row.status, p_status;
    END IF;
  END IF;

  RETURN QUERY
  UPDATE ghm.campaign
     SET title = next_title,
         status = next_status,
         updated_at = now()
   WHERE ghm.campaign.id = current_row.id
  RETURNING
    ghm.campaign.id,
    ghm.campaign.business_id,
    ghm.campaign.created_by_account_id,
    ghm.campaign.title,
    ghm.campaign.status,
    ghm.campaign.created_at,
    ghm.campaign.updated_at;
END;
$$;

ALTER FUNCTION ghm.update_campaign(bigint, bigint, text, text)
  OWNER TO ghm_schema_owner;
REVOKE ALL ON FUNCTION ghm.update_campaign(bigint, bigint, text, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION ghm.update_campaign(bigint, bigint, text, text) TO ghm_runtime;
