-- Construct the provider-neutral GHM Trust score capability.
-- Construction-only. No production migration or product cutover is authorized.
-- Source: Connect migration 20260721170743_establish_trust_and_saved_business_contracts.sql

CREATE TABLE ghm.trust_score (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

  business_id bigint NOT NULL
    REFERENCES ghm.business(id)
    ON DELETE CASCADE,

  profile_complete smallint NOT NULL DEFAULT 0,
  phone_verified smallint NOT NULL DEFAULT 0,
  email_verified smallint NOT NULL DEFAULT 0,
  id_verified smallint NOT NULL DEFAULT 0,
  cipc_verified smallint NOT NULL DEFAULT 0,
  vat_verified smallint NOT NULL DEFAULT 0,
  insurance_verified smallint NOT NULL DEFAULT 0,
  reviews_score smallint NOT NULL DEFAULT 0,
  completed_projects smallint NOT NULL DEFAULT 0,
  total_score smallint NOT NULL DEFAULT 0,
  trust_level text NOT NULL DEFAULT 'bronze',
  last_updated timestamptz NOT NULL DEFAULT now(),
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),

  CONSTRAINT trust_score_business_unique
    UNIQUE (business_id),

  CONSTRAINT trust_score_profile_complete_check
    CHECK (profile_complete BETWEEN 0 AND 15),

  CONSTRAINT trust_score_phone_verified_check
    CHECK (phone_verified BETWEEN 0 AND 10),

  CONSTRAINT trust_score_email_verified_check
    CHECK (email_verified BETWEEN 0 AND 10),

  CONSTRAINT trust_score_id_verified_check
    CHECK (id_verified BETWEEN 0 AND 10),

  CONSTRAINT trust_score_cipc_verified_check
    CHECK (cipc_verified BETWEEN 0 AND 10),

  CONSTRAINT trust_score_vat_verified_check
    CHECK (vat_verified BETWEEN 0 AND 5),

  CONSTRAINT trust_score_insurance_verified_check
    CHECK (insurance_verified BETWEEN 0 AND 15),

  CONSTRAINT trust_score_reviews_score_check
    CHECK (reviews_score BETWEEN 0 AND 15),

  CONSTRAINT trust_score_completed_projects_check
    CHECK (completed_projects BETWEEN 0 AND 10),

  CONSTRAINT trust_score_total_score_check
    CHECK (total_score BETWEEN 0 AND 100),

  CONSTRAINT trust_score_trust_level_check
    CHECK (trust_level IN ('bronze', 'silver', 'gold', 'platinum'))
);

CREATE INDEX trust_score_level_total_idx
  ON ghm.trust_score (trust_level, total_score DESC);

CREATE INDEX trust_score_last_updated_idx
  ON ghm.trust_score (last_updated DESC);

ALTER TABLE ghm.trust_score OWNER TO ghm_schema_owner;

COMMENT ON TABLE ghm.trust_score IS
  'Canonical calculated Trust score for a business.';

CREATE OR REPLACE FUNCTION ghm.set_trust_score_updated_at()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, ghm
AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

ALTER FUNCTION ghm.set_trust_score_updated_at() OWNER TO ghm_schema_owner;
REVOKE ALL ON FUNCTION ghm.set_trust_score_updated_at() FROM PUBLIC;

CREATE TRIGGER trust_score_set_updated_at
BEFORE UPDATE ON ghm.trust_score
FOR EACH ROW
EXECUTE FUNCTION ghm.set_trust_score_updated_at();

GRANT USAGE ON SCHEMA ghm TO ghm_runtime;

GRANT SELECT
  ON TABLE ghm.trust_score
  TO ghm_runtime;

REVOKE INSERT, UPDATE, DELETE
  ON TABLE ghm.trust_score
  FROM ghm_runtime;

GRANT USAGE ON SEQUENCE ghm.trust_score_id_seq TO ghm_runtime;

-- Runtime mutation is exposed only through this governed calculation function.
-- p_account_id must be AuthContext.userId. Connect trust.read maps to active
-- owner/administrator membership. Missing Connect Business profile columns
-- (description/phone/email/insurance_verified/jobs_completed) score as 0 until
-- a separately authorized Business profile extension establishes them.
CREATE OR REPLACE FUNCTION ghm.calculate_business_trust_score(
  p_account_id bigint,
  p_business_id bigint
)
RETURNS ghm.trust_score
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = pg_catalog, ghm
AS $$
DECLARE
  target_business ghm.business%ROWTYPE;
  calculated_profile_complete smallint;
  calculated_phone_verified smallint;
  calculated_email_verified smallint;
  calculated_id_verified smallint;
  calculated_cipc_verified smallint;
  calculated_vat_verified smallint;
  calculated_insurance_verified smallint;
  calculated_reviews_score smallint;
  calculated_completed_projects smallint;
  calculated_total_score smallint;
  calculated_trust_level text;
  calculated_score ghm.trust_score%ROWTYPE;
BEGIN
  IF p_account_id IS NULL OR p_account_id <= 0 THEN
    RAISE EXCEPTION 'Authentication is required to calculate a Trust score.';
  END IF;

  IF p_business_id IS NULL OR p_business_id <= 0 THEN
    RAISE EXCEPTION 'Business ID must be a positive integer';
  END IF;

  IF NOT EXISTS (
    SELECT 1
    FROM ghm.business_membership
    WHERE business_id = p_business_id
      AND account_id = p_account_id
      AND membership_status = 'active'
      AND membership_role IN ('owner', 'administrator')
  ) THEN
    RAISE EXCEPTION 'You do not have permission to calculate this business Trust score.';
  END IF;

  SELECT *
    INTO target_business
    FROM ghm.business
   WHERE id = p_business_id;

  IF NOT FOUND THEN
    RAISE EXCEPTION 'Business was not found.';
  END IF;

  -- Connect: profile_complete from businesses.description. GHM Business first-slice
  -- has no description column; equivalent to empty → 0.
  calculated_profile_complete := 0;

  -- Connect: phone_verified from businesses.phone presence. Column absent → 0.
  calculated_phone_verified := 0;

  -- Connect: email_verified from businesses.email presence. Column absent → 0.
  calculated_email_verified := 0;

  -- Connect: remain zero until authoritative evidence contracts exist.
  calculated_id_verified := 0;
  calculated_cipc_verified := 0;
  calculated_vat_verified := 0;

  -- Connect: insurance_verified boolean. Column absent → 0.
  calculated_insurance_verified := 0;

  calculated_reviews_score :=
    least(
      greatest(
        round(
          coalesce(target_business.rating, 0) * 3
        )::integer,
        0
      ),
      15
    )::smallint;

  -- Connect: completed_projects from jobs_completed. Column absent → 0.
  calculated_completed_projects := 0;

  calculated_total_score := (
    calculated_profile_complete
    + calculated_phone_verified
    + calculated_email_verified
    + calculated_id_verified
    + calculated_cipc_verified
    + calculated_vat_verified
    + calculated_insurance_verified
    + calculated_reviews_score
    + calculated_completed_projects
  )::smallint;

  calculated_trust_level :=
    CASE
      WHEN calculated_total_score >= 80 THEN 'platinum'
      WHEN calculated_total_score >= 60 THEN 'gold'
      WHEN calculated_total_score >= 40 THEN 'silver'
      ELSE 'bronze'
    END;

  INSERT INTO ghm.trust_score (
    business_id,
    profile_complete,
    phone_verified,
    email_verified,
    id_verified,
    cipc_verified,
    vat_verified,
    insurance_verified,
    reviews_score,
    completed_projects,
    total_score,
    trust_level,
    last_updated
  )
  VALUES (
    p_business_id,
    calculated_profile_complete,
    calculated_phone_verified,
    calculated_email_verified,
    calculated_id_verified,
    calculated_cipc_verified,
    calculated_vat_verified,
    calculated_insurance_verified,
    calculated_reviews_score,
    calculated_completed_projects,
    calculated_total_score,
    calculated_trust_level,
    now()
  )
  ON CONFLICT (business_id)
  DO UPDATE
  SET
    profile_complete = EXCLUDED.profile_complete,
    phone_verified = EXCLUDED.phone_verified,
    email_verified = EXCLUDED.email_verified,
    id_verified = EXCLUDED.id_verified,
    cipc_verified = EXCLUDED.cipc_verified,
    vat_verified = EXCLUDED.vat_verified,
    insurance_verified = EXCLUDED.insurance_verified,
    reviews_score = EXCLUDED.reviews_score,
    completed_projects = EXCLUDED.completed_projects,
    total_score = EXCLUDED.total_score,
    trust_level = EXCLUDED.trust_level,
    last_updated = EXCLUDED.last_updated
  RETURNING *
  INTO calculated_score;

  RETURN calculated_score;
END;
$$;

ALTER FUNCTION ghm.calculate_business_trust_score(bigint, bigint)
  OWNER TO ghm_schema_owner;
REVOKE ALL ON FUNCTION ghm.calculate_business_trust_score(bigint, bigint) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION ghm.calculate_business_trust_score(bigint, bigint) TO ghm_runtime;
